-- Seed de conteudo P.Q.P. (gerado automaticamente)
-- Rode DEPOIS do supabase-schema.sql

create unique index if not exists perguntas_texto_key on perguntas (texto);
create unique index if not exists respostas_texto_key on respostas (texto);

-- PERGUNTAS (507)
insert into perguntas (texto, categoria, espacos, status) values
('O que o Papai Noel faz quando ninguém está olhando? ______', 'geral', 1, 'publicado'),
('A melhor cura para uma ressaca é ______.', 'geral', 1, 'publicado'),
('Qual é o segredo que o anfitrião esconde de todos? ______', 'geral', 1, 'publicado'),
('O que não pode faltar em um velório animado? ______', 'geral', 1, 'publicado'),
('Qual é a nova modalidade das Olimpíadas do submundo? ______', 'geral', 1, 'publicado'),
('O que minha mãe encontrou na minha gaveta que me deixou sem herança? ______', 'geral', 1, 'publicado'),
('Para seduzir alguém, eu sempre uso ______.', 'geral', 1, 'publicado'),
('O motivo real do fim do mundo será ______.', 'geral', 1, 'publicado'),
('O que os políticos fazem no tempo livre? ______', 'geral', 1, 'publicado'),
('A primeira coisa que farei quando ganhar na loteria é ______.', 'geral', 1, 'publicado'),
('Qual é a tatuagem mais arrependida do mundo? ______', 'geral', 1, 'publicado'),
('O que os gatos planejam nas reuniões noturnas? ______', 'geral', 1, 'publicado'),
('Como o anfitrião realmente perdeu a virgindade? ______', 'geral', 1, 'publicado'),
('O prato principal do inferno é ______.', 'geral', 1, 'publicado'),
('Minha habilidade inútil de super-herói é ______.', 'geral', 1, 'publicado'),
('O que faz o anfitrião chorar no banho? ______', 'geral', 1, 'publicado'),
('A última coisa que eu gostaria de ouvir antes de morrer é ______.', 'geral', 1, 'publicado'),
('Qual é o cheiro oficial do desespero? ______', 'geral', 1, 'publicado'),
('O que o Elon Musk vai levar para Marte escondido? ______', 'geral', 1, 'publicado'),
('A desculpa perfeita para faltar ao trabalho é ______.', 'geral', 1, 'publicado'),
('Se eu pudesse legalizar qualquer coisa, seria ______.', 'geral', 1, 'publicado'),
('O que acontece no camarim do show de calouros? ______', 'geral', 1, 'publicado'),
('Qual é a busca mais bizarra no meu histórico do Google? ______', 'geral', 1, 'publicado'),
('O que o anfitrião faz para ganhar um dinheiro extra? ______', 'geral', 1, 'publicado'),
('Qual é o ingrediente secreto da coxinha da esquina? ______', 'geral', 1, 'publicado'),
('Na sala de espera do hospital, todo mundo ficou olhando quando ______ apareceu gritando.', 'hospital', 1, 'publicado'),
('O médico entrou no quarto e a primeira coisa que perguntou foi sobre ______.', 'hospital', 1, 'publicado'),
('A enfermeira quase caiu de susto ao ver ______ dentro da UTI.', 'hospital', 1, 'publicado'),
('No plantão da madrugada, o que mais assustou o hospital inteiro foi ______.', 'hospital', 1, 'publicado'),
('A receita médica mais estranha que já vi tinha escrito ______.', 'hospital', 1, 'publicado'),
('No corredor do hospital, o paciente do quarto 302 só falava sobre ______.', 'hospital', 1, 'publicado'),
('A ficha de internação pedia o motivo da visita e a pessoa escreveu ______.', 'hospital', 1, 'publicado'),
('O cheiro mais forte que já senti numa ala hospitalar foi de ______.', 'hospital', 1, 'publicado'),
('Na sala de cirurgia, o silêncio foi quebrado quando alguém gritou ______.', 'hospital', 1, 'publicado'),
('O boletim médico do paciente famoso revelou que ele tinha ______.', 'hospital', 1, 'publicado'),
('A visita ao hospital virou circo quando a família trouxe ______.', 'hospital', 1, 'publicado'),
('O aviso na porta da enfermaria dizia: proibido entrar com ______.', 'hospital', 1, 'publicado'),
('Todo plantonista de hospital tem uma história sobre ______ no elevador.', 'hospital', 1, 'publicado'),
('O que mais irrita um enfermeiro de plantão é quando o paciente pede ______.', 'hospital', 1, 'publicado'),
('Na recepção do hospital particular, cobraram uma taxa extra por ______.', 'hospital', 1, 'publicado'),
('O exame de sangue voltou com um resultado bizarro apontando ______.', 'hospital', 1, 'publicado'),
('Na ala psiquiátrica, o paciente mais calmo era o que falava sobre ______.', 'hospital', 1, 'publicado'),
('O que nunca pode faltar num kit de primeiros socorros é ______.', 'hospital', 1, 'publicado'),
('A ambulância chegou correndo por causa de ______.', 'hospital', 1, 'publicado'),
('No raio-x apareceu algo que ninguém esperava: ______.', 'hospital', 1, 'publicado'),
('A vizinha de quarto no hospital não parava de reclamar de ______.', 'hospital', 1, 'publicado'),
('O médico residente aprendeu na marra que nunca deve ______.', 'hospital', 1, 'publicado'),
('Durante a cirurgia, o anestesista comentou baixinho sobre ______.', 'hospital', 1, 'publicado'),
('A sala de espera lotou depois que espalharam boato sobre ______.', 'hospital', 1, 'publicado'),
('O prontuário médico mais engraçado que já vi mencionava ______.', 'hospital', 1, 'publicado'),
('No berçário, as enfermeiras apostaram sobre qual bebê ia nascer parecido com ______.', 'hospital', 1, 'publicado'),
('A dieta do hospital proibiu terminantemente ______.', 'hospital', 1, 'publicado'),
('O paciente recém-operado insistiu em levantar da cama por causa de ______.', 'hospital', 1, 'publicado'),
('Na sala de emergência, gritaram para trazer ______ com urgência.', 'hospital', 1, 'publicado'),
('O laudo médico trouxe uma recomendação inusitada: evitar ______.', 'hospital', 1, 'publicado'),
('Todo hospital tem aquele funcionário que esconde ______ no armário.', 'hospital', 1, 'publicado'),
('A enfermaria virou motivo de piada depois que descobriram ______ escondido.', 'hospital', 1, 'publicado'),
('O soro do paciente foi trocado às pressas por causa de ______.', 'hospital', 1, 'publicado'),
('No corredor da maternidade, o pai desmaiou ao ouvir sobre ______.', 'hospital', 1, 'publicado'),
('A camisola de hospital ficou famosa por causa de ______.', 'hospital', 1, 'publicado'),
('O médico plantonista jura que já viu de tudo, inclusive ______.', 'hospital', 1, 'publicado'),
('A campainha de emergência tocou sem parar por causa de ______.', 'hospital', 1, 'publicado'),
('O paciente do apartamento VIP só reclamava da falta de ______.', 'hospital', 1, 'publicado'),
('Na consulta de rotina, o médico ficou surpreso ao perguntar sobre ______.', 'hospital', 1, 'publicado'),
('O hospital teve que chamar segurança depois que alguém trouxe ______.', 'hospital', 1, 'publicado'),
('A fila do pronto-socorro parou tudo quando apareceu ______.', 'hospital', 1, 'publicado'),
('No relatório de alta, o médico escreveu que o paciente teve alta por causa de ______.', 'hospital', 1, 'publicado'),
('Na roda de mães do parquinho, o assunto do dia foi ______.', 'parquinho', 1, 'publicado'),
('O pai que ficou no banco do parquinho o tempo todo só falava de ______.', 'parquinho', 1, 'publicado'),
('A discussão mais acalorada do playground foi sobre quem trouxe ______.', 'parquinho', 1, 'publicado'),
('O grupo de WhatsApp das mães da escolinha bombou depois que alguém postou ______.', 'parquinho', 1, 'publicado'),
('Na hora do lanche coletivo, ninguém esperava que a mãe trouxesse ______.', 'parquinho', 1, 'publicado'),
('O zelador do parquinho jura que já viu de tudo, inclusive ______.', 'parquinho', 1, 'publicado'),
('A competição de quem tem o filho mais esperto virou vergonha depois de ______.', 'parquinho', 1, 'publicado'),
('No aniversário de criança no parquinho, o que mais deu o que falar foi ______.', 'parquinho', 1, 'publicado'),
('A vizinha fofoqueira do playground espalhou que o casal ali da esquina tinha ______.', 'parquinho', 1, 'publicado'),
('O balanço quebrou justamente na hora em que alguém tentou mostrar ______.', 'parquinho', 1, 'publicado'),
('Na reunião de pais, o assunto que ninguém esperava discutir foi ______.', 'parquinho', 1, 'publicado'),
('O pai coruja trouxe pro parquinho um equipamento que ninguém pediu: ______.', 'parquinho', 1, 'publicado'),
('A mãe do prédio ao lado ficou famosa no bairro por causa de ______.', 'parquinho', 1, 'publicado'),
('O escorregador ficou interditado depois que descobriram ______.', 'parquinho', 1, 'publicado'),
('Na disputa por quem organiza a festa junina da escolinha, rolou boato sobre ______.', 'parquinho', 1, 'publicado'),
('O grupo de pais decidiu banir do playground qualquer um que trouxesse ______.', 'parquinho', 1, 'publicado'),
('A caixa de areia virou assunto sério depois que acharam ______ escondido nela.', 'parquinho', 1, 'publicado'),
('No churrasco de confraternização das famílias, o climão começou quando alguém mencionou ______.', 'parquinho', 1, 'publicado'),
('A gangorra parou de funcionar bem na hora em que dois pais discutiam sobre ______.', 'parquinho', 1, 'publicado'),
('O condomínio proibiu o uso do parquinho depois do escândalo envolvendo ______.', 'parquinho', 1, 'publicado'),
('Na fila pra pegar as crianças, duas mães quase brigaram por causa de ______.', 'parquinho', 1, 'publicado'),
('O aviso novo na entrada do playground diz: proibido trazer ______.', 'parquinho', 1, 'publicado'),
('A avó que fica de olho nos netos contou pra todo mundo sobre ______.', 'parquinho', 1, 'publicado'),
('O grupo de pais do time de futebol infantil rachou depois de uma discussão sobre ______.', 'parquinho', 1, 'publicado'),
('Na live dos pais no Instagram, o comentário mais bizarro foi sobre ______.', 'parquinho', 1, 'publicado'),
('O parquinho virou point às escondidas depois que descobriram ______ ali de madrugada.', 'parquinho', 1, 'publicado'),
('A síndica colocou câmera nova no playground por causa de ______.', 'parquinho', 1, 'publicado'),
('Na roda de conversa dos pais, ninguém esperava a confissão sobre ______.', 'parquinho', 1, 'publicado'),
('O casal que sempre discute alto no parquinho tava brigando por causa de ______.', 'parquinho', 1, 'publicado'),
('A professora da escolinha levou um susto quando um pai apareceu com ______.', 'parquinho', 1, 'publicado'),
('No dia das crianças, o brinde mais estranho que distribuíram foi ______.', 'parquinho', 1, 'publicado'),
('A vizinha do playground jura que viu um pai fazendo ______ escondido.', 'parquinho', 1, 'publicado'),
('O grupo dos pais organizou uma vaquinha suspeita pra comprar ______.', 'parquinho', 1, 'publicado'),
('Na disputa de quem é o pai mais descolado, um deles apareceu com ______.', 'parquinho', 1, 'publicado'),
('O portão do parquinho emperrou bem na hora em que alguém tentava esconder ______.', 'parquinho', 1, 'publicado'),
('A reunião de condomínio virou climão quando debateram sobre ______ no playground.', 'parquinho', 1, 'publicado'),
('O pai que trabalha home office aproveitou o parquinho pra fazer ______.', 'parquinho', 1, 'publicado'),
('Na hora da soneca das crianças, os pais aproveitaram pra fofocar sobre ______.', 'parquinho', 1, 'publicado'),
('O grupo das mães decidiu criar uma regra nova contra ______ no playground.', 'parquinho', 1, 'publicado'),
('A campainha do prédio tocou sem parar porque alguém viu ______ no parquinho de madrugada.', 'parquinho', 1, 'publicado'),
('Na sala dos professores, o assunto mais comentado da semana foi ______.', 'escola', 1, 'publicado'),
('O diretor chamou os pais na escola por causa de ______.', 'escola', 1, 'publicado'),
('Na prova surpresa, a pergunta mais estranha foi sobre ______.', 'escola', 1, 'publicado'),
('O boletim voltou pra casa com uma anotação sobre ______.', 'escola', 1, 'publicado'),
('Na hora do recreio, rolou treta generalizada por causa de ______.', 'escola', 1, 'publicado'),
('O professor de educação física perdeu a paciência com ______.', 'escola', 1, 'publicado'),
('Na festa junina da escola, a barraca mais concorrida vendia ______.', 'escola', 1, 'publicado'),
('O bilhete que a escola mandou pros pais falava sobre ______.', 'escola', 1, 'publicado'),
('Na formatura, o discurso mais inesperado mencionou ______.', 'escola', 1, 'publicado'),
('O grêmio estudantil organizou uma campanha polêmica sobre ______.', 'escola', 1, 'publicado'),
('Na sala de aula, o professor confiscou ______ de um aluno.', 'escola', 1, 'publicado'),
('O cantinho da leitura foi interditado depois que acharam ______.', 'escola', 1, 'publicado'),
('Na reunião de pais e mestres, ninguém esperava ouvir sobre ______.', 'escola', 1, 'publicado'),
('O uniforme da escola ficou famoso depois que alguém bordou ______ nele.', 'escola', 1, 'publicado'),
('Na excursão escolar, o ônibus quase virou bagunça por causa de ______.', 'escola', 1, 'publicado'),
('O intervalo da escola virou assunto de grupo de pais depois de ______.', 'escola', 1, 'publicado'),
('Na apresentação de talentos, o número mais bizarro envolveu ______.', 'escola', 1, 'publicado'),
('O professor substituto levou um choque no primeiro dia ao ver ______.', 'escola', 1, 'publicado'),
('Na cantina da escola, o item mais vendido esse ano foi ______.', 'escola', 1, 'publicado'),
('O mural da escola foi pichado com uma frase sobre ______.', 'escola', 1, 'publicado'),
('Na hora cívica, o hino foi interrompido por causa de ______.', 'escola', 1, 'publicado'),
('O laboratório de ciências virou bagunça depois que um aluno trouxe ______.', 'escola', 1, 'publicado'),
('Na fila da merenda, a maior confusão foi sobre quem levou ______.', 'escola', 1, 'publicado'),
('O coordenador pedagógico teve que intervir por causa de ______.', 'escola', 1, 'publicado'),
('Na gincana da escola, a prova mais absurda pedia pra trazer ______.', 'escola', 1, 'publicado'),
('O quadro de avisos anunciou uma regra nova proibindo ______.', 'escola', 1, 'publicado'),
('Na sala de detenção, o motivo mais engraçado que já ouvi foi ______.', 'escola', 1, 'publicado'),
('O professor de história contou uma curiosidade sobre ______ que ninguém esqueceu.', 'escola', 1, 'publicado'),
('Na hora do intervalo, o pátio parou pra ver ______ acontecendo.', 'escola', 1, 'publicado'),
('O time de vôlei da escola comemorou a vitória trazendo ______.', 'escola', 1, 'publicado'),
('Na feira de ciências, o projeto mais criativo (e estranho) envolvia ______.', 'escola', 1, 'publicado'),
('O grupo de WhatsApp da turma bombou depois que alguém mandou ______.', 'escola', 1, 'publicado'),
('Na sala de informática, o professor pegou um aluno pesquisando ______.', 'escola', 1, 'publicado'),
('O uniforme sumiu do vestiário e apareceu no meio de ______.', 'escola', 1, 'publicado'),
('Na aula de artes, a obra mais polêmica retratava ______.', 'escola', 1, 'publicado'),
('O inspetor de alunos correu pelo corredor atrás de ______.', 'escola', 1, 'publicado'),
('Na semana cultural, a apresentação que mais chocou a plateia foi sobre ______.', 'escola', 1, 'publicado'),
('O aluno nota dez surpreendeu todo mundo ao confessar ______.', 'escola', 1, 'publicado'),
('Na roda de amigos do colégio, o segredo mais guardado era sobre ______.', 'escola', 1, 'publicado'),
('O sinal da escola tocou bem na hora em que todo mundo descobriu ______.', 'escola', 1, 'publicado'),
('Na resenha da faculdade, o assunto que bombou foi ______.', 'faculdade', 1, 'publicado'),
('O professor cancelou a prova depois de descobrir ______.', 'faculdade', 1, 'publicado'),
('Na república estudantil, a regra mais respeitada era nunca mexer em ______.', 'faculdade', 1, 'publicado'),
('O trabalho em grupo desandou quando alguém sugeriu ______.', 'faculdade', 1, 'publicado'),
('Na calourada, o trote mais absurdo envolveu ______.', 'faculdade', 1, 'publicado'),
('O diretório acadêmico organizou uma festa que ficou famosa por causa de ______.', 'faculdade', 1, 'publicado'),
('Na apresentação de TCC, a banca ficou em choque com ______.', 'faculdade', 1, 'publicado'),
('O estágio obrigatório virou pesadelo por causa de ______.', 'faculdade', 1, 'publicado'),
('Na biblioteca da faculdade, pegaram um aluno fazendo ______ escondido.', 'faculdade', 1, 'publicado'),
('O grupo do WhatsApp da turma explodiu depois que postaram ______.', 'faculdade', 1, 'publicado'),
('Na prova final, o cola mais criativo que já vi tinha ______ escrito.', 'faculdade', 1, 'publicado'),
('O professor titular é famoso na faculdade por causa de ______.', 'faculdade', 1, 'publicado'),
('Na festa da atlética, rolou treta generalizada envolvendo ______.', 'faculdade', 1, 'publicado'),
('O currículo do aluno mais gabaritado da turma incluía ______.', 'faculdade', 1, 'publicado'),
('Na sala de aula, o debate mais acalorado do semestre foi sobre ______.', 'faculdade', 1, 'publicado'),
('O laboratório da faculdade foi interditado depois que descobriram ______.', 'faculdade', 1, 'publicado'),
('Na formatura, o paraninfo escolhido surpreendeu todo mundo por causa de ______.', 'faculdade', 1, 'publicado'),
('O intercâmbio acadêmico rendeu uma história inesquecível sobre ______.', 'faculdade', 1, 'publicado'),
('Na resenha de sexta, o item que nunca pode faltar é ______.', 'faculdade', 1, 'publicado'),
('O monitor da disciplina foi flagrado fazendo ______ durante a aula.', 'faculdade', 1, 'publicado'),
('Na moradia estudantil, a regra número um era nunca esconder ______.', 'faculdade', 1, 'publicado'),
('O grupo de pesquisa publicou um artigo bizarro sobre ______.', 'faculdade', 1, 'publicado'),
('Na apresentação de seminário, o slide mais constrangedor mostrava ______.', 'faculdade', 1, 'publicado'),
('O aluno bolsista revelou o segredo por trás de ______.', 'faculdade', 1, 'publicado'),
('Na sala do centro acadêmico, guardavam escondido ______.', 'faculdade', 1, 'publicado'),
('O professor recém-contratado ficou famoso por causa de ______.', 'faculdade', 1, 'publicado'),
('Na formatura da turma, o brinde mais absurdo foi feito com ______.', 'faculdade', 1, 'publicado'),
('O estágio de verão virou meme depois que alguém postou ______.', 'faculdade', 1, 'publicado'),
('Na disciplina de ética, discutiram um caso real envolvendo ______.', 'faculdade', 1, 'publicado'),
('O grêmio universitário organizou uma campanha polêmica sobre ______.', 'faculdade', 1, 'publicado'),
('Na república, a lista de compras coletiva sempre incluía ______.', 'faculdade', 1, 'publicado'),
('O professor visitante contou uma história inacreditável sobre ______.', 'faculdade', 1, 'publicado'),
('Na prova oral, o examinador ficou sem reação ao ouvir sobre ______.', 'faculdade', 1, 'publicado'),
('O aluno mais popular do curso ficou famoso por causa de ______.', 'faculdade', 1, 'publicado'),
('Na semana de recepção dos calouros, a dinâmica mais estranha envolveu ______.', 'faculdade', 1, 'publicado'),
('O trabalho de conclusão de curso quase foi reprovado por causa de ______.', 'faculdade', 1, 'publicado'),
('Na sala dos professores, comentaram baixinho sobre ______.', 'faculdade', 1, 'publicado'),
('O aplicativo de caronas da faculdade ficou famoso depois de ______.', 'faculdade', 1, 'publicado'),
('Na festa de encerramento do semestre, o brinde surpresa foi ______.', 'faculdade', 1, 'publicado'),
('O coordenador do curso teve que se explicar sobre ______.', 'faculdade', 1, 'publicado'),
('Na reunião de família, o assunto que ninguém queria tocar foi ______.', 'casa', 1, 'publicado'),
('A gaveta trancada do armário escondia ______.', 'casa', 1, 'publicado'),
('No almoço de domingo, a discussão começou por causa de ______.', 'casa', 1, 'publicado'),
('A empregada encontrou ______ embaixo da cama.', 'casa', 1, 'publicado'),
('No grupo de família do WhatsApp, a bomba da semana foi ______.', 'casa', 1, 'publicado'),
('A geladeira estava vazia, só tinha ______.', 'casa', 1, 'publicado'),
('No quintal, o vizinho jura que viu ______ pendurado no varal.', 'casa', 1, 'publicado'),
('A sogra chegou de surpresa e encontrou ______ na sala.', 'casa', 1, 'publicado'),
('No aniversário de casamento, o presente mais estranho foi ______.', 'casa', 1, 'publicado'),
('A faxina de fim de ano revelou ______ escondido no sótão.', 'casa', 1, 'publicado'),
('No jantar em família, ninguém esperava que alguém trouxesse ______ à mesa.', 'casa', 1, 'publicado'),
('A lista de compras do mês incluía, sem explicação, ______.', 'casa', 1, 'publicado'),
('No churrasco de família, o climão começou quando surgiu ______.', 'casa', 1, 'publicado'),
('A caixa de lembranças da vovó guardava ______.', 'casa', 1, 'publicado'),
('No quarto dos fundos, encontraram uma coleção secreta de ______.', 'casa', 1, 'publicado'),
('A conta de luz veio alta esse mês por causa de ______.', 'casa', 1, 'publicado'),
('No porta-retrato da sala, tinha uma foto de ______ que ninguém explicou.', 'casa', 1, 'publicado'),
('A discussão de casal mais clássica é sempre sobre ______.', 'casa', 1, 'publicado'),
('No Natal em família, o presente que causou climão foi ______.', 'casa', 1, 'publicado'),
('A vizinha bisbilhoteira contou pro prédio inteiro sobre ______.', 'casa', 1, 'publicado'),
('No armário do banheiro, tinha escondido ______.', 'casa', 1, 'publicado'),
('A reforma da casa parou por causa de uma descoberta chocante: ______.', 'casa', 1, 'publicado'),
('No grupo da família, a tia mandou uma mensagem confusa sobre ______.', 'casa', 1, 'publicado'),
('A mudança pra casa nova revelou ______ que o antigo dono deixou.', 'casa', 1, 'publicado'),
('No fundo do quintal, o cachorro desenterrou ______.', 'casa', 1, 'publicado'),
('A sala de estar virou bagunça depois da festa surpresa com ______.', 'casa', 1, 'publicado'),
('No jogo de tabuleiro em família, a briga começou por causa de ______.', 'casa', 1, 'publicado'),
('A esposa descobriu, no bolso da calça, ______.', 'casa', 1, 'publicado'),
('No porão da casa, tinha uma caixa lacrada só escrito ______.', 'casa', 1, 'publicado'),
('A reunião de condomínio virou climão por causa de ______.', 'casa', 1, 'publicado'),
('No churrasco de aniversário, o tio bêbado contou sobre ______.', 'casa', 1, 'publicado'),
('A troca de fraldas do bebê revelou um susto: ______.', 'casa', 1, 'publicado'),
('No feriado prolongado, a família toda brigou por causa de ______.', 'casa', 1, 'publicado'),
('A sogra deixou um bilhete na geladeira falando de ______.', 'casa', 1, 'publicado'),
('No aniversário de 15 anos, o presente mais bizarro veio dentro de ______.', 'casa', 1, 'publicado'),
('A empregada pediu demissão depois de encontrar ______ na lavanderia.', 'casa', 1, 'publicado'),
('No jantar de reveillon, o brinde mais estranho foi feito com ______.', 'casa', 1, 'publicado'),
('A vovó contou, sem pudor nenhum, a história de quando ______.', 'casa', 1, 'publicado'),
('No quintal do vizinho, ninguém sabia explicar o barulho de ______.', 'casa', 1, 'publicado'),
('A herança da família causou briga por causa de ______.', 'casa', 1, 'publicado'),
('No meio do culto, o pastor parou o sermão por causa de ______.', 'igreja', 1, 'publicado'),
('A irmã da terceira fileira desmaiou ao ver ______.', 'igreja', 1, 'publicado'),
('Na escola bíblica infantil, a tia explicou de um jeito estranho sobre ______.', 'igreja', 1, 'publicado'),
('No coral da igreja, a treta começou porque alguém queria cantar sobre ______.', 'igreja', 1, 'publicado'),
('Na oferta do domingo, o pastor pediu especificamente por ______.', 'igreja', 1, 'publicado'),
('O casamento na igreja parou quando alguém gritou sobre ______.', 'igreja', 1, 'publicado'),
('Na reunião de jovens, o assunto proibido da noite foi ______.', 'igreja', 1, 'publicado'),
('O diácono foi flagrado escondendo ______ atrás do altar.', 'igreja', 1, 'publicado'),
('Na vigília de oração, ninguém esperava um pedido tão específico: ______.', 'igreja', 1, 'publicado'),
('O grupo de WhatsApp da igreja bombou depois que postaram ______.', 'igreja', 1, 'publicado'),
('Na procissão, o andor quase caiu por causa de ______.', 'igreja', 1, 'publicado'),
('A irmã fofoqueira contou pra congregação inteira sobre ______.', 'igreja', 1, 'publicado'),
('No batizado, o bebê chorou desesperado assim que viu ______.', 'igreja', 1, 'publicado'),
('Na feira beneficente da igreja, o item mais vendido foi ______.', 'igreja', 1, 'publicado'),
('O pastor visitante ficou famoso na cidade por causa de ______.', 'igreja', 1, 'publicado'),
('Na confissão, o segredo mais chocante que já ouviram foi sobre ______.', 'igreja', 1, 'publicado'),
('O casamento comunitário virou assunto da cidade por causa de ______.', 'igreja', 1, 'publicado'),
('Na reunião de líderes, decidiram proibir ______ nas dependências da igreja.', 'igreja', 1, 'publicado'),
('O grupo de louvor cancelou o ensaio depois que descobriram ______.', 'igreja', 1, 'publicado'),
('Na festa de aniversário da igreja, o bolo veio decorado com ______.', 'igreja', 1, 'publicado'),
('A irmã responsável pela cozinha comunitária escondia ______ na despensa.', 'igreja', 1, 'publicado'),
('No retiro espiritual, o momento mais surreal foi quando apareceu ______.', 'igreja', 1, 'publicado'),
('O sistema de som falhou bem na hora do anúncio sobre ______.', 'igreja', 1, 'publicado'),
('Na campanha do agasalho, doaram, sem querer, ______.', 'igreja', 1, 'publicado'),
('O casal mais tradicional da igreja foi flagrado fazendo ______.', 'igreja', 1, 'publicado'),
('Na escola dominical, uma criança perguntou algo que deixou todo mundo sem resposta: ______.', 'igreja', 1, 'publicado'),
('O culto de gratidão virou climão depois que alguém testemunhou sobre ______.', 'igreja', 1, 'publicado'),
('Na sala dos fundos da igreja, guardavam escondido ______.', 'igreja', 1, 'publicado'),
('O pastor pediu silêncio total antes de anunciar ______.', 'igreja', 1, 'publicado'),
('Na quermesse, a barraca mais concorrida vendia ______.', 'igreja', 1, 'publicado'),
('O microfone ficou aberto sem querer e todo mundo ouviu sobre ______.', 'igreja', 1, 'publicado'),
('Na reunião de casais, a dinâmica mais constrangedora envolveu ______.', 'igreja', 1, 'publicado'),
('O sacristão contou, baixinho, o segredo por trás de ______.', 'igreja', 1, 'publicado'),
('Na celebração de aniversário da igreja, trouxeram de surpresa ______.', 'igreja', 1, 'publicado'),
('O grupo de intercessão orou especificamente por causa de ______.', 'igreja', 1, 'publicado'),
('Na saída do culto, o comentário mais absurdo foi sobre ______.', 'igreja', 1, 'publicado'),
('O evento beneficente arrecadou fundos vendendo ______.', 'igreja', 1, 'publicado'),
('Na reforma do templo, encontraram escondido atrás da parede ______.', 'igreja', 1, 'publicado'),
('O anúncio no boletim dominical mencionava, sem explicação, ______.', 'igreja', 1, 'publicado'),
('Na despedida do pastor, o presente de gratidão foi ______.', 'igreja', 1, 'publicado'),
('No terreiro, a gira parou por um instante quando chegou ______.', 'terreiro', 1, 'publicado'),
('Na cozinha do terreiro, o cheiro mais gostoso da festa vinha de ______.', 'terreiro', 1, 'publicado'),
('Na roda de axé, todo mundo ficou surpreso ao ver ______.', 'terreiro', 1, 'publicado'),
('No dia da festa de Iemanjá, alguém apareceu trazendo ______.', 'terreiro', 1, 'publicado'),
('Na sala de consulta, a mãe de santo perguntou logo de cara sobre ______.', 'terreiro', 1, 'publicado'),
('No salão do terreiro, a decoração mais chamativa daquele ano foi ______.', 'terreiro', 1, 'publicado'),
('Depois da gira, o assunto que rolou solto na cozinha comunitária foi ______.', 'terreiro', 1, 'publicado'),
('Na roda de conversa antes da festa, contaram a história de quando ______.', 'terreiro', 1, 'publicado'),
('No terreiro, ninguém esperava que a oferenda incluísse ______.', 'terreiro', 1, 'publicado'),
('Na noite de festa, o ponto de comida mais concorrido foi o que tinha ______.', 'terreiro', 1, 'publicado'),
('No batuque, o tambor parou de repente por causa de ______.', 'terreiro', 1, 'publicado'),
('Na entrada do terreiro, deixaram um aviso simpático sobre ______.', 'terreiro', 1, 'publicado'),
('Na roda dos mais velhos, contaram um causo inesquecível sobre ______.', 'terreiro', 1, 'publicado'),
('No dia de limpeza do terreiro, encontraram escondido ______.', 'terreiro', 1, 'publicado'),
('Na festa de aniversário do terreiro, o bolo comunitário veio com ______.', 'terreiro', 1, 'publicado'),
('Na cozinha, a disputa da noite foi sobre quem fez o melhor ______.', 'terreiro', 1, 'publicado'),
('No salão de festas do terreiro, a decoração surpreendeu todo mundo com ______.', 'terreiro', 1, 'publicado'),
('Na despedida da festa, o presente simbólico distribuído foi ______.', 'terreiro', 1, 'publicado'),
('No grupo de WhatsApp da casa, a novidade da semana foi ______.', 'terreiro', 1, 'publicado'),
('Na roda de visitantes, a pergunta mais engraçada foi sobre ______.', 'terreiro', 1, 'publicado'),
('Depois da festa, a limpeza do salão revelou ______ esquecido num canto.', 'terreiro', 1, 'publicado'),
('Na feira de artesanato do terreiro, o item mais vendido foi ______.', 'terreiro', 1, 'publicado'),
('No dia de arrumação, alguém trouxe de surpresa ______ pra ajudar.', 'terreiro', 1, 'publicado'),
('Na cozinha comunitária, a receita secreta da casa levava ______.', 'terreiro', 1, 'publicado'),
('Na confraternização de fim de ano, o presente amigo oculto mais engraçado foi ______.', 'terreiro', 1, 'publicado'),
('Na roda de história, contaram sobre a vez em que ______ aconteceu na festa.', 'terreiro', 1, 'publicado'),
('No salão, a música que mais animou a galera falava sobre ______.', 'terreiro', 1, 'publicado'),
('Na organização da festa, a comissão decidiu incluir ______ no cardápio.', 'terreiro', 1, 'publicado'),
('No fim da celebração, o agradecimento especial foi por causa de ______.', 'terreiro', 1, 'publicado'),
('Na feira beneficente, arrecadaram fundos vendendo ______.', 'terreiro', 1, 'publicado'),
('Na roda de conversa da tarde, o boato do bairro era sobre ______.', 'terreiro', 1, 'publicado'),
('No dia de doação de cestas básicas, alguém contribuiu com ______.', 'terreiro', 1, 'publicado'),
('Na cozinha, a discussão mais engraçada foi sobre o tempero de ______.', 'terreiro', 1, 'publicado'),
('No salão decorado pra festa, o detalhe que mais chamou atenção foi ______.', 'terreiro', 1, 'publicado'),
('Na roda dos jovens da casa, o assunto do momento era ______.', 'terreiro', 1, 'publicado'),
('Depois da celebração, o comentário mais engraçado da noite foi sobre ______.', 'terreiro', 1, 'publicado'),
('Na organização da confraternização, decidiram surpreender todo mundo com ______.', 'terreiro', 1, 'publicado'),
('No bazar beneficente, o item mais disputado da tarde foi ______.', 'terreiro', 1, 'publicado'),
('Na despedida de ano, o brinde especial da casa foi feito com ______.', 'terreiro', 1, 'publicado'),
('Na roda de agradecimento, todo mundo comentou sobre ______.', 'terreiro', 1, 'publicado'),
('Na praia lotada, todo mundo virou pra ver ______ passando.', 'praia', 1, 'publicado'),
('O guarda-vidas correu quando alguém gritou por causa de ______.', 'praia', 1, 'publicado'),
('Na barraca de praia, o item mais pedido do dia foi ______.', 'praia', 1, 'publicado'),
('O vendedor ambulante ficou famoso na praia por vender ______.', 'praia', 1, 'publicado'),
('Na areia, a briga por espaço começou por causa de ______.', 'praia', 1, 'publicado'),
('O quiosque mais concorrido da orla vendia ______.', 'praia', 1, 'publicado'),
('Na virada de ano na praia, o brinde mais estranho foi feito com ______.', 'praia', 1, 'publicado'),
('O jogo de futevôlei parou quando apareceu ______ no meio da quadra.', 'praia', 1, 'publicado'),
('Na barraca ao lado, o grupo estava comemorando por causa de ______.', 'praia', 1, 'publicado'),
('O mar devolveu na areia algo que ninguém esperava: ______.', 'praia', 1, 'publicado'),
('Na praia de nudismo, o comentário mais engraçado foi sobre ______.', 'praia', 1, 'publicado'),
('O vendedor de picolé quase caiu ao ver ______ na areia.', 'praia', 1, 'publicado'),
('Na roda de amigos, a história mais absurda contada na praia foi sobre ______.', 'praia', 1, 'publicado'),
('O pôr do sol foi interrompido quando alguém trouxe ______.', 'praia', 1, 'publicado'),
('Na fila do banheiro público da praia, rolou treta por causa de ______.', 'praia', 1, 'publicado'),
('O barraqueiro proibiu terminantemente que trouxessem ______ pra barraca.', 'praia', 1, 'publicado'),
('Na praia deserta, o casal foi flagrado fazendo ______.', 'praia', 1, 'publicado'),
('O caiaque virou no meio do mar por causa de ______.', 'praia', 1, 'publicado'),
('Na feira de artesanato da orla, o item mais estranho à venda era ______.', 'praia', 1, 'publicado'),
('O carro de som da praia anunciou, sem explicação, ______.', 'praia', 1, 'publicado'),
('Na disputa de vôlei de praia, o climão começou por causa de ______.', 'praia', 1, 'publicado'),
('O quiosque decidiu criar um drink novo chamado ______.', 'praia', 1, 'publicado'),
('Na praia do nudismo, a placa avisava: proibido ______.', 'praia', 1, 'publicado'),
('O jangadeiro contou uma história inacreditável sobre ______.', 'praia', 1, 'publicado'),
('Na temporada de verão, o bar da praia ficou famoso por causa de ______.', 'praia', 1, 'publicado'),
('O grupo de amigos alugou uma casa na praia só pra fazer ______.', 'praia', 1, 'publicado'),
('Na disputa do castelo de areia mais bonito, o vencedor usou ______.', 'praia', 1, 'publicado'),
('O salva-vidas resgatou um turista que tinha ido nadar por causa de ______.', 'praia', 1, 'publicado'),
('Na barraca vizinha, discutiam alto sobre quem trouxe ______.', 'praia', 1, 'publicado'),
('O sol forte não impediu ninguém de continuar fazendo ______ na areia.', 'praia', 1, 'publicado'),
('Na feira noturna da orla, o show mais inesperado envolveu ______.', 'praia', 1, 'publicado'),
('O trailer de comida na praia ficou famoso pelo seu ______ especial.', 'praia', 1, 'publicado'),
('Na canoagem em grupo, alguém caiu na água por causa de ______.', 'praia', 1, 'publicado'),
('O réveillon na praia terminou com todo mundo comentando sobre ______.', 'praia', 1, 'publicado'),
('Na disputa por sombra na areia, o climão foi por causa de ______.', 'praia', 1, 'publicado'),
('O grupo de surfistas ficou famoso na praia por causa de ______.', 'praia', 1, 'publicado'),
('Na fila do quiosque, o pedido mais estranho da tarde foi ______.', 'praia', 1, 'publicado'),
('O carro estacionado na orla foi flagrado com ______ dentro.', 'praia', 1, 'publicado'),
('Na praia lotada de feriado, o barulho que mais incomodou foi ______.', 'praia', 1, 'publicado'),
('O pescador contou que já viu de tudo no mar, inclusive ______.', 'praia', 1, 'publicado'),
('No metrô lotado, ninguém esperava ver ______ dentro do vagão.', 'metro', 1, 'publicado'),
('A voz do alto-falante anunciou um atraso por causa de ______.', 'metro', 1, 'publicado'),
('No horário de pico, a maior confusão da plataforma foi por causa de ______.', 'metro', 1, 'publicado'),
('O passageiro do banco ao lado começou a falar sozinho sobre ______.', 'metro', 1, 'publicado'),
('Na catraca do metrô, alguém tentou passar escondendo ______.', 'metro', 1, 'publicado'),
('O vagão lotado parou de repente por causa de ______.', 'metro', 1, 'publicado'),
('Na plataforma, o vendedor ambulante estava oferecendo ______.', 'metro', 1, 'publicado'),
('O funcionário da estação teve que chamar segurança por causa de ______.', 'metro', 1, 'publicado'),
('No metrô da madrugada, o passageiro mais estranho carregava ______.', 'metro', 1, 'publicado'),
('A porta do vagão fechou bem na hora em que alguém gritava sobre ______.', 'metro', 1, 'publicado'),
('No elevador da estação, ficaram presos por causa de ______.', 'metro', 1, 'publicado'),
('O grafite mais famoso da estação retratava ______.', 'metro', 1, 'publicado'),
('Na roleta de entrada, travou justamente quando alguém tentava levar ______.', 'metro', 1, 'publicado'),
('O passageiro distraído esqueceu ______ dentro do vagão.', 'metro', 1, 'publicado'),
('Na fila do bilhete, a discussão começou por causa de ______.', 'metro', 1, 'publicado'),
('O músico que toca na estação ficou famoso por cantar sobre ______.', 'metro', 1, 'publicado'),
('No vagão feminino, rolou climão por causa de ______.', 'metro', 1, 'publicado'),
('A estação foi interditada temporariamente por causa de ______.', 'metro', 1, 'publicado'),
('No metrô, o cheiro mais forte do vagão vinha de ______.', 'metro', 1, 'publicado'),
('O passageiro apertado no rush comentou baixinho sobre ______.', 'metro', 1, 'publicado'),
('Na escada rolante, alguém deixou cair ______ e virou zoeira geral.', 'metro', 1, 'publicado'),
('O guarda da estação recolheu, sem explicação, ______ de um passageiro.', 'metro', 1, 'publicado'),
('No banco reservado, a discussão foi sobre quem tinha mais direito a ______.', 'metro', 1, 'publicado'),
('A campainha da porta tocou insistente por causa de ______.', 'metro', 1, 'publicado'),
('No túnel escuro entre estações, alguém jurou ter visto ______.', 'metro', 1, 'publicado'),
('O anúncio de emergência pediu calma por causa de ______.', 'metro', 1, 'publicado'),
('Na saída da estação, um grupo estava vendendo ______ escondido.', 'metro', 1, 'publicado'),
('O passageiro chorou desesperadamente ao perder ______ no metrô.', 'metro', 1, 'publicado'),
('Na plataforma lotada, todo mundo empurrou por causa de ______.', 'metro', 1, 'publicado'),
('O trem parou entre estações e o clima ficou tenso por causa de ______.', 'metro', 1, 'publicado'),
('No mapa da linha, alguém rabiscou uma piada sobre ______.', 'metro', 1, 'publicado'),
('A bilheteria fechou mais cedo por causa de ______.', 'metro', 1, 'publicado'),
('No vagão silencioso, o barulho mais irritante veio de ______.', 'metro', 1, 'publicado'),
('O passageiro do celular alto estava falando sem parar sobre ______.', 'metro', 1, 'publicado'),
('Na hora do rush, um grupo se organizou pra vender ______ escondido dos fiscais.', 'metro', 1, 'publicado'),
('O elevador quebrado da estação virou motivo de reclamação sobre ______.', 'metro', 1, 'publicado'),
('No fim de linha, o funcionário encontrou ______ esquecido no último vagão.', 'metro', 1, 'publicado'),
('A fila da bilheteria rendeu uma discussão generalizada sobre ______.', 'metro', 1, 'publicado'),
('No metrô lotado, o cheiro de perfume forte era de alguém carregando ______.', 'metro', 1, 'publicado'),
('A estação mais movimentada da cidade ficou famosa por causa de ______.', 'metro', 1, 'publicado'),
('Na feira livre, o barraqueiro mais popular vendia ______.', 'feira', 1, 'publicado'),
('A discussão de preço na banca de frutas começou por causa de ______.', 'feira', 1, 'publicado'),
('Na feira, a fila mais comprida da manhã era pra comprar ______.', 'feira', 1, 'publicado'),
('O feirante gritava anunciando promoção de ______.', 'feira', 1, 'publicado'),
('Na roda de conversa entre os feirantes, o assunto do dia era ______.', 'feira', 1, 'publicado'),
('A cliente reclamona da feira sempre discute sobre ______.', 'feira', 1, 'publicado'),
('Na banca de peixe, o cheiro mais forte da manhã vinha de ______.', 'feira', 1, 'publicado'),
('O carrinho de compras quebrou no meio da feira carregando ______.', 'feira', 1, 'publicado'),
('Na feira orgânica, o item mais caro (e estranho) era ______.', 'feira', 1, 'publicado'),
('O feirante mais antigo do bairro contou uma história sobre ______.', 'feira', 1, 'publicado'),
('Na disputa por espaço na barraca, o climão foi por causa de ______.', 'feira', 1, 'publicado'),
('A senhora que sempre pechincha levou de graça ______.', 'feira', 1, 'publicado'),
('Na feira noturna, o food truck mais concorrido vendia ______.', 'feira', 1, 'publicado'),
('O barraqueiro de tempero ficou famoso na região por causa de ______.', 'feira', 1, 'publicado'),
('Na feira de domingo, a maior fila da manhã era pra experimentar ______.', 'feira', 1, 'publicado'),
('O ambulante que passa vendendo ______ é conhecido de todo mundo.', 'feira', 1, 'publicado'),
('Na banca de flores, o pedido mais estranho da semana foi ______.', 'feira', 1, 'publicado'),
('O feirante contou que já viu de tudo, inclusive ______ sendo vendido escondido.', 'feira', 1, 'publicado'),
('Na feira de artesanato, o item mais bizarro à venda era ______.', 'feira', 1, 'publicado'),
('A cliente distraída esqueceu ______ em cima da banca.', 'feira', 1, 'publicado'),
('Na roda de fofoca das feirantes, o assunto mais comentado foi ______.', 'feira', 1, 'publicado'),
('O caminhão de entrega chegou atrasado por causa de ______.', 'feira', 1, 'publicado'),
('Na feira do produtor, o item que mais vendeu esse mês foi ______.', 'feira', 1, 'publicado'),
('O feirante mais gente boa da região sempre dá de brinde ______.', 'feira', 1, 'publicado'),
('Na banca de queijos, o cliente pediu pra provar antes de comprar ______.', 'feira', 1, 'publicado'),
('A discussão na feira sobre quem chegou primeiro na fila envolveu ______.', 'feira', 1, 'publicado'),
('O food truck novo da feira ficou famoso pelo seu ______ especial.', 'feira', 1, 'publicado'),
('Na feira de troca, alguém trocou o carro por ______.', 'feira', 1, 'publicado'),
('O guarda municipal teve que intervir na feira por causa de ______.', 'feira', 1, 'publicado'),
('Na banca de temperos, o cheiro mais forte da manhã era de ______.', 'feira', 1, 'publicado'),
('A senhora do bairro compra toda semana, sem falta, ______.', 'feira', 1, 'publicado'),
('Na feira, o vendedor de CD pirata também vendia escondido ______.', 'feira', 1, 'publicado'),
('O motorista do caminhão de hortifruti reclamou de ______ atrapalhando a entrega.', 'feira', 1, 'publicado'),
('Na feira de rua, o show ambulante fez todo mundo parar pra ver ______.', 'feira', 1, 'publicado'),
('O barraqueiro mais rabugento nunca aceita reclamação sobre ______.', 'feira', 1, 'publicado'),
('Na feira de sábado, o item que sumiu mais rápido das bancas foi ______.', 'feira', 1, 'publicado'),
('A vendedora de doces caseiros ficou famosa por causa de ______.', 'feira', 1, 'publicado'),
('Na negociação de última hora, o feirante topou trocar por ______.', 'feira', 1, 'publicado'),
('O cheiro de café fresco da feira se misturava com o de ______.', 'feira', 1, 'publicado'),
('Na feira, a maior confusão do dia foi por causa da fila pra comprar ______.', 'feira', 1, 'publicado'),
('Na esquina do bairro, todo mundo comentava sobre ______.', 'rua', 1, 'publicado'),
('O carro parou no meio da rua por causa de ______.', 'rua', 1, 'publicado'),
('Na calçada, o vizinho jurou ter visto ______ passando de madrugada.', 'rua', 1, 'publicado'),
('O ambulante que vende picolé na rua ficou famoso por causa de ______.', 'rua', 1, 'publicado'),
('Na rua sem saída, o barulho que mais incomodava os moradores era ______.', 'rua', 1, 'publicado'),
('O poste de luz quebrado virou assunto do grupo de WhatsApp por causa de ______.', 'rua', 1, 'publicado'),
('Na esquina do bar, a treta começou por causa de ______.', 'rua', 1, 'publicado'),
('O carteiro contou que já viu de tudo nas ruas, inclusive ______.', 'rua', 1, 'publicado'),
('Na rua de terra, o buraco maior escondia ______.', 'rua', 1, 'publicado'),
('O guarda de trânsito parou o carro por causa de ______.', 'rua', 1, 'publicado'),
('Na calçada estreita, a briga por espaço foi por causa de ______.', 'rua', 1, 'publicado'),
('O grafite novo na parede da esquina retratava ______.', 'rua', 1, 'publicado'),
('Na rua do comércio, a loja mais visitada vendia ______.', 'rua', 1, 'publicado'),
('O vizinho barulhento é famoso na rua por causa de ______.', 'rua', 1, 'publicado'),
('Na madrugada, o barulho estranho vinha lá da rua de trás por causa de ______.', 'rua', 1, 'publicado'),
('O carro de som passou anunciando, sem explicação, ______.', 'rua', 1, 'publicado'),
('Na feira de rua improvisada, o item mais vendido foi ______.', 'rua', 1, 'publicado'),
('O motoboy quase caiu da moto desviando de ______.', 'rua', 1, 'publicado'),
('Na rua movimentada, o engarrafamento foi por causa de ______.', 'rua', 1, 'publicado'),
('O mendigo da esquina sempre pede, educadamente, ______.', 'rua', 1, 'publicado'),
('Na calçada da padaria, a fila da manhã só falava sobre ______.', 'rua', 1, 'publicado'),
('O buraco na rua virou piscina depois da chuva e alguém jogou ______ dentro.', 'rua', 1, 'publicado'),
('Na rua do bairro, o carro estacionado errado tinha ______ visível pela janela.', 'rua', 1, 'publicado'),
('O flanelinha da esquina cobra caro, mas garante cuidar de ______.', 'rua', 1, 'publicado'),
('Na esquina, o grupo de amigos ficou até tarde discutindo sobre ______.', 'rua', 1, 'publicado'),
('O poste virou ponto de referência depois que colaram cartaz sobre ______.', 'rua', 1, 'publicado'),
('Na rua deserta à noite, o único som era de ______.', 'rua', 1, 'publicado'),
('O carro alugado quebrou no meio da rua com ______ no banco de trás.', 'rua', 1, 'publicado'),
('Na calçada, o cachorro do vizinho fugiu correndo atrás de ______.', 'rua', 1, 'publicado'),
('O bloco de carnaval de rua ficou famoso por causa de ______.', 'rua', 1, 'publicado'),
('Na rua principal, o comércio fechou mais cedo por causa de ______.', 'rua', 1, 'publicado'),
('O caminhão de mudança bloqueou a rua carregando ______.', 'rua', 1, 'publicado'),
('Na esquina do colégio, os pais discutiam sobre ______.', 'rua', 1, 'publicado'),
('O muro pichado da rua tinha escrito ______ em letras gigantes.', 'rua', 1, 'publicado'),
('Na rua de pedestres, o artista de rua chamou atenção fazendo ______.', 'rua', 1, 'publicado'),
('O carro de polícia parou na esquina por causa de ______.', 'rua', 1, 'publicado'),
('Na calçada molhada, alguém escorregou segurando ______.', 'rua', 1, 'publicado'),
('O vendedor de rua foi embora correndo depois que viu ______.', 'rua', 1, 'publicado'),
('Na disputa por vaga de garagem na rua, o climão foi por causa de ______.', 'rua', 1, 'publicado'),
('O bairro inteiro comentou, por dias, sobre ______ que apareceu na rua.', 'rua', 1, 'publicado'),
('No campo do bairro, a pelada de domingo parou por causa de ______.', 'futebol', 1, 'publicado'),
('O juiz amador marcou pênalti duvidoso e a torcida gritou sobre ______.', 'futebol', 1, 'publicado'),
('No vestiário, o técnico deu um discurso inesquecível sobre ______.', 'futebol', 1, 'publicado'),
('Na arquibancada, a torcida organizada trouxe uma faixa escrita ______.', 'futebol', 1, 'publicado'),
('No intervalo do jogo, o comentário mais absurdo foi sobre ______.', 'futebol', 1, 'publicado'),
('O goleiro amador jura que só tomou o gol por causa de ______.', 'futebol', 1, 'publicado'),
('Na final do campeonato de várzea, o climão começou por causa de ______.', 'futebol', 1, 'publicado'),
('O gramado do campo estava um caos por causa de ______.', 'futebol', 1, 'publicado'),
('Na disputa de pênaltis, a torcida ficou em silêncio esperando ______.', 'futebol', 1, 'publicado'),
('O time reserva comemorou o empate trazendo ______ pro vestiário.', 'futebol', 1, 'publicado'),
('Na lateral do campo, o cambista estava vendendo ______ escondido.', 'futebol', 1, 'publicado'),
('O narrador amador do campeonato de bairro comentou sobre ______ ao vivo.', 'futebol', 1, 'publicado'),
('Na confraternização depois do jogo, o churrasco ficou famoso por causa de ______.', 'futebol', 1, 'publicado'),
('O uniforme do time do bairro foi trocado de última hora por causa de ______.', 'futebol', 1, 'publicado'),
('Na disputa acirrada, o técnico tirou o jogador de campo por causa de ______.', 'futebol', 1, 'publicado'),
('O campo alagou de chuva e ainda assim rolou o jogo por causa de ______.', 'futebol', 1, 'publicado'),
('Na arquibancada de madeira, a torcida apostou uma rodada de ______.', 'futebol', 1, 'publicado'),
('O juiz expulsou um jogador depois que ele reclamou sobre ______.', 'futebol', 1, 'publicado'),
('Na quadra society, a pelada de sexta-feira sempre termina com ______.', 'futebol', 1, 'publicado'),
('O time de várzea patrocinado pelo bar ganhou de presente ______.', 'futebol', 1, 'publicado'),
('Na comemoração do gol, o jogador tirou a camisa mostrando ______.', 'futebol', 1, 'publicado'),
('O vestiário do time visitante virou assunto depois que descobriram ______.', 'futebol', 1, 'publicado'),
('Na disputa pelo título amador, a torcida rival provocou com ______.', 'futebol', 1, 'publicado'),
('O gramado sintético do campo novo custou caro por causa de ______.', 'futebol', 1, 'publicado'),
('Na cobrança de falta, a barreira se formou torta por causa de ______.', 'futebol', 1, 'publicado'),
('O árbitro auxiliar levantou a bandeirinha alertando sobre ______.', 'futebol', 1, 'publicado'),
('Na roda de resenha pós-jogo, o assunto mais comentado foi ______.', 'futebol', 1, 'publicado'),
('O time amador contratou um reforço famoso por causa de ______.', 'futebol', 1, 'publicado'),
('Na disputa pela taça, o presidente do clube prometeu ______ pro time campeão.', 'futebol', 1, 'publicado'),
('O bar ao lado do campo lotou no dia da final vendendo ______.', 'futebol', 1, 'publicado'),
('Na cobrança de escanteio, a confusão começou por causa de ______.', 'futebol', 1, 'publicado'),
('O treino de sábado foi cancelado de última hora por causa de ______.', 'futebol', 1, 'publicado'),
('Na disputa de pênaltis decisiva, o goleiro comemorou segurando ______.', 'futebol', 1, 'publicado'),
('O time feminino do bairro ficou famoso na cidade por causa de ______.', 'futebol', 1, 'publicado'),
('Na saída do campo, a torcida discutia acaloradamente sobre ______.', 'futebol', 1, 'publicado'),
('O uniforme numerado sumiu do vestiário junto com ______.', 'futebol', 1, 'publicado'),
('Na quadra de futsal, a pelada da firma sempre rende histórias sobre ______.', 'futebol', 1, 'publicado'),
('O técnico do time de várzea jura nunca ter visto algo igual a ______.', 'futebol', 1, 'publicado'),
('Na comemoração do campeonato, o troféu foi erguido junto com ______.', 'futebol', 1, 'publicado'),
('O campinho de terra do bairro ficou famoso na cidade por causa de ______.', 'futebol', 1, 'publicado')
on conflict (texto) do nothing;

-- RESPOSTAS (192)
insert into respostas (texto, status) values
('um motoboy com fé em Deus', 'publicado'),
('a vergonha alheia da família toda', 'publicado'),
('aquele silêncio constrangedor', 'publicado'),
('meu cartão de crédito chorando baixinho', 'publicado'),
('a vizinha fofoqueira do prédio', 'publicado'),
('um pastor cobrando dízimo em dobro', 'publicado'),
('meu ex me chamando às 2 da manhã', 'publicado'),
('a fila do INSS às 5 da manhã', 'publicado'),
('um pix errado de R$ 3.000', 'publicado'),
('a playlist secreta do tio no churrasco', 'publicado'),
('aquele áudio de 8 minutos que ninguém ouviu', 'publicado'),
('o cheiro de churrasco vindo do vizinho', 'publicado'),
('uma crise existencial no meio do rodízio', 'publicado'),
('o grupo da família no zap às 6h', 'publicado'),
('um santinho de político puxando conversa', 'publicado'),
('a promoção que só tem letra miúda', 'publicado'),
('meu horóscopo mentindo descaradamente', 'publicado'),
('um influenciador vendendo curso de nada', 'publicado'),
('a régua 22 do cabeleireiro', 'publicado'),
('o silêncio depois do ''a gente precisa conversar''', 'publicado'),
('uma sogra com superpoderes de fofoca', 'publicado'),
('o boleto vencido há três meses', 'publicado'),
('aquele beijo técnico no Carnaval', 'publicado'),
('um chinelo voando com precisão cirúrgica', 'publicado'),
('a fé cega no cartão de crédito', 'publicado'),
('meu joelho estalando igual pipoca', 'publicado'),
('o WhatsApp da empresa fingindo ser urgente', 'publicado'),
('uma primeira comunhão regada a cerveja', 'publicado'),
('o tio que sabe tudo de política', 'publicado'),
('a vergonha de dar ''oi'' pra pessoa errada', 'publicado'),
('um exorcismo mal ensaiado', 'publicado'),
('a fila do banco que não anda', 'publicado'),
('meu currículo mentindo sobre Excel', 'publicado'),
('um bafo de cebola em plena entrevista', 'publicado'),
('a ressaca moral de domingo de manhã', 'publicado'),
('um professor particular de sedução', 'publicado'),
('a raiva de perder o ônibus por 2 segundos', 'publicado'),
('um pastor cobrando PIX no culto', 'publicado'),
('aquele abraço que dura tempo demais', 'publicado'),
('a saideira que virou madrugada inteira', 'publicado'),
('um cupido desempregado', 'publicado'),
('a fofoca que rendeu três novelas', 'publicado'),
('meu estagiário fingindo que entendeu', 'publicado'),
('um sermão de duas horas sobre nada', 'publicado'),
('a vergonha de rir no funeral errado', 'publicado'),
('um paçoquinha filosofando na roda de amigos', 'publicado'),
('o Uber cancelando na sua cara', 'publicado'),
('uma multa de trânsito por excesso de charme', 'publicado'),
('a promessa de malhar segunda-feira', 'publicado'),
('um exorcista freelancer', 'publicado'),
('a fila do posto de saúde às 4 da manhã', 'publicado'),
('meu quinto café do dia me julgando', 'publicado'),
('um bêbado declarando amor eterno', 'publicado'),
('a vergonha de cantar desafinado no chuveiro', 'publicado'),
('aquele stalker discreto do Instagram', 'publicado'),
('um pastor com Ferrari importada', 'publicado'),
('a saudade que só aparece à meia-noite', 'publicado'),
('um chefe que confunde humildade com humilhação', 'publicado'),
('meu terapeuta anotando tudo calado', 'publicado'),
('a bênção que veio em forma de boleto', 'publicado'),
('um cunhado emprestando dinheiro sem devolver', 'publicado'),
('aquele ''kkk'' seco de quem tá puto', 'publicado'),
('a coragem que só vem depois da terceira cerveja', 'publicado'),
('um karaokê que virou tragédia grega', 'publicado'),
('a saudação constrangedora no elevador', 'publicado'),
('meu Wi-Fi caindo no pior momento possível', 'publicado'),
('um vizinho que reforma a casa às 7h de domingo', 'publicado'),
('a fé inabalável de quem aposta na Mega-Sena', 'publicado'),
('um crush que só dá bom dia', 'publicado'),
('a vergonha de escorregar na igreja lotada', 'publicado'),
('meu álibi furado igual peneira', 'publicado'),
('um professor de ioga estressado', 'publicado'),
('a raiva de descobrir que era spam', 'publicado'),
('aquele parente que só aparece pra pedir favor', 'publicado'),
('um político prometendo emprego pra todo mundo', 'publicado'),
('a cara de paisagem quando alguém te chama pra ajudar a mudar', 'publicado'),
('um amigo que some quando a conta chega', 'publicado'),
('a autoestima depois de três taças de vinho', 'publicado'),
('meu chefe achando que WhatsApp é hora extra', 'publicado'),
('um casamento que durou menos que o buffet', 'publicado'),
('a fila do caixa eletrônico dia 5', 'publicado'),
('um evangélico discutindo futebol', 'publicado'),
('aquele oi visualizado sem resposta', 'publicado'),
('a vergonha de tropeçar no tapete vermelho da vida', 'publicado'),
('um vidente cobrando parcelado', 'publicado'),
('meu joelho avisando a mudança de tempo', 'publicado'),
('a saudade que aperta no fim de semana', 'publicado'),
('um sogro competindo no churrasco', 'publicado'),
('a fé de quem confia no motorista de aplicativo', 'publicado'),
('aquele grupo da faculdade que virou cemitério', 'publicado'),
('um padre comentando a novela das 9', 'publicado'),
('a vergonha de arrotar numa reunião importante', 'publicado'),
('meu orgulho falando mais alto que a razão', 'publicado'),
('um tio zap desmentindo cientista', 'publicado'),
('a raiva de perder o joguinho pro sobrinho', 'publicado'),
('um flerte capenga na academia', 'publicado'),
('a coragem líquida de sexta-feira', 'publicado'),
('meu banco cobrando taxa por respirar', 'publicado'),
('um exorcismo com playlist de forró', 'publicado'),
('a vergonha de dar risada no momento errado', 'publicado'),
('um chefe chamando reunião às 18h', 'publicado'),
('a fila do supermercado no dia do pagamento', 'publicado'),
('meu horóscopo culpando Mercúrio de novo', 'publicado'),
('um pastor vendendo água benta em dose dupla', 'publicado'),
('a saudade que vira stalker no Instagram', 'publicado'),
('um professor que confunde nota com vingança', 'publicado'),
('a vergonha de cair no meio da pista de dança', 'publicado'),
('meu ex aparecendo nos stories de todo mundo', 'publicado'),
('um cupido de plantão no grupo da família', 'publicado'),
('a fé em dieta que começa segunda que vem', 'publicado'),
('um chinelo que resolve briga de irmão', 'publicado'),
('a raiva de descobrir o preço do Uber surge', 'publicado'),
('aquele parente que só fala de política no almoço', 'publicado'),
('um professor particular de paquera', 'publicado'),
('a vergonha de mandar áudio errado pro chefe', 'publicado'),
('meu estômago roncando na hora do silêncio', 'publicado'),
('um pastor cobrando cartão de crédito no altar', 'publicado'),
('a saudade disfarçada de curtida no post antigo', 'publicado'),
('um amigo que empresta carregador e some', 'publicado'),
('a fila do busão lotado às 6h', 'publicado'),
('meu currículo com foto de 10 anos atrás', 'publicado'),
('um karaokê improvisado no ônibus', 'publicado'),
('a raiva de trocar o Wi-Fi e ninguém avisar a senha nova', 'publicado'),
('um sogro contando a mesma piada há 20 anos', 'publicado'),
('a coragem de responder o chefe em maiúsculas', 'publicado'),
('meu abraço apertado demais no primeiro encontro', 'publicado'),
('um pastor prometendo milagre parcelado', 'publicado'),
('a fé de quem acredita em previsão do tempo', 'publicado'),
('aquele silêncio na chamada de vídeo travada', 'publicado'),
('um tio contando vantagem sobre os anos 90', 'publicado'),
('a vergonha de cochilar em reunião online', 'publicado'),
('meu vizinho testando o alarme às 3 da manhã', 'publicado'),
('um crush comentando só os stories dos outros', 'publicado'),
('a raiva de ficar sem sinal na hora do plot twist', 'publicado'),
('um padre torcendo escondido pro time rival', 'publicado'),
('a saudade que só some com pizza', 'publicado'),
('um evangélico dublando funk baixinho', 'publicado'),
('a coragem de terminar por mensagem de voz', 'publicado'),
('meu chefe chamando ''só um minutinho'' às 17h58', 'publicado'),
('um pastor com anel maior que aliança de noiva', 'publicado'),
('a fila do RH pra pedir aumento', 'publicado'),
('aquele match que só chama pra jogo', 'publicado'),
('um tio zap virando repórter de plantão', 'publicado'),
('a vergonha de escorregar de chinelo no shopping', 'publicado'),
('meu orgulho travando o pedido de desculpas', 'publicado'),
('um cunhado que só aparece na hora da churrasqueira', 'publicado'),
('a raiva de descobrir que o boleto já venceu', 'publicado'),
('um exorcista cobrando por PIX parcelado', 'publicado'),
('a saudade que ataca depois da terceira dose', 'publicado'),
('um professor comentando a vida amorosa da turma', 'publicado'),
('a vergonha de mandar beijo pro grupo errado', 'publicado'),
('meu estagiário respondendo ''ok'' pra tudo', 'publicado'),
('um pastor discursando sobre Bitcoin', 'publicado'),
('a fila da farmácia às 23h59', 'publicado'),
('aquele ''visto'' sem resposta há três dias', 'publicado'),
('um sogro perguntando quando vem neto', 'publicado'),
('a coragem de pedir aumento numa sexta-feira', 'publicado'),
('meu vizinho comprando furadeira nova todo mês', 'publicado'),
('um crush que só curte, nunca comenta', 'publicado'),
('a raiva de perder o sinal no jogo decisivo', 'publicado'),
('um padre comentando o preço da gasolina', 'publicado'),
('a vergonha de rir alto no cinema silencioso', 'publicado'),
('meu ex comentando indireta no status', 'publicado'),
('um tio contando piada que ninguém pediu', 'publicado'),
('a fé de quem acredita em dieta de segunda', 'publicado'),
('um pastor cobrando fé em espécie', 'publicado'),
('a saudade que vira ligação bêbada', 'publicado'),
('aquele grupo do trabalho que só fala besteira', 'publicado'),
('um professor de dança se achando', 'publicado'),
('a vergonha de escorregar na saída da igreja', 'publicado'),
('meu chefe achando que fim de semana é feriado', 'publicado'),
('um cunhado emprestando ferramenta e sumindo', 'publicado'),
('a raiva de perder o desconto por um minuto', 'publicado'),
('um vidente de shopping cobrando por PIX', 'publicado'),
('a coragem de mandar oi pra ex às 3 da manhã', 'publicado'),
('um padre com playlist secreta de pagode', 'publicado'),
('a fila da rodoviária no fim de ano', 'publicado'),
('aquele silêncio depois de um puxão de orelha', 'publicado'),
('um tio comentando sobre o time errado', 'publicado'),
('a vergonha de gritar gol no time perdedor', 'publicado'),
('meu vizinho testando bateria elétrica às 6h', 'publicado'),
('um pastor prometendo prosperidade em dobro', 'publicado'),
('a saudade que some com um café requentado', 'publicado'),
('um sogro comparando genro com sobrinho', 'publicado'),
('a raiva de descobrir que a promoção acabou ontem', 'publicado'),
('um crush comentando meme de outra pessoa', 'publicado'),
('a coragem de responder áudio com áudio maior', 'publicado'),
('meu chefe achando reunião de sábado normal', 'publicado'),
('um cunhado que só chega na hora da sobremesa', 'publicado'),
('a fé em resolução de ano novo que dura três dias', 'publicado'),
('um pastor discursando sobre criptomoeda no culto', 'publicado'),
('a fila do caixa que sempre trava no cartão', 'publicado')
on conflict (texto) do nothing;
