
export interface QuestionCategory {
  id: string;
  label: string;
  questions: string[];
}

export const QUESTION_CATEGORIES: QuestionCategory[] = [
  {
    id: 'geral',
    label: 'Geral',
    questions: [
      "O que o Papai Noel faz quando ninguém está olhando? ______",
      "A melhor cura para uma ressaca é ______.",
      "Qual é o segredo que o anfitrião esconde de todos? ______",
      "O que não pode faltar em um velório animado? ______",
      "Qual é a nova modalidade das Olimpíadas do submundo? ______",
      "O que minha mãe encontrou na minha gaveta que me deixou sem herança? ______",
      "Para seduzir alguém, eu sempre uso ______.",
      "O motivo real do fim do mundo será ______.",
      "O que os políticos fazem no tempo livre? ______",
      "A primeira coisa que farei quando ganhar na loteria é ______.",
      "Qual é a tatuagem mais arrependida do mundo? ______",
      "O que os gatos planejam nas reuniões noturnas? ______",
      "Como o anfitrião realmente perdeu a virgindade? ______",
      "O prato principal do inferno é ______.",
      "Minha habilidade inútil de super-herói é ______.",
      "O que faz o anfitrião chorar no banho? ______",
      "A última coisa que eu gostaria de ouvir antes de morrer é ______.",
      "Qual é o cheiro oficial do desespero? ______",
      "O que o Elon Musk vai levar para Marte escondido? ______",
      "A desculpa perfeita para faltar ao trabalho é ______.",
      "Se eu pudesse legalizar qualquer coisa, seria ______.",
      "O que acontece no camarim do show de calouros? ______",
      "Qual é a busca mais bizarra no meu histórico do Google? ______",
      "O que o anfitrião faz para ganhar um dinheiro extra? ______",
      "Qual é o ingrediente secreto da coxinha da esquina? ______"
    ]
  },
  {
    id: 'hospital',
    label: 'Hospital',
    questions: [
      "Na sala de espera do hospital, todo mundo ficou olhando quando ______ apareceu gritando.",
      "O médico entrou no quarto e a primeira coisa que perguntou foi sobre ______.",
      "A enfermeira quase caiu de susto ao ver ______ dentro da UTI.",
      "No plantão da madrugada, o que mais assustou o hospital inteiro foi ______.",
      "A receita médica mais estranha que já vi tinha escrito ______.",
      "No corredor do hospital, o paciente do quarto 302 só falava sobre ______.",
      "A ficha de internação pedia o motivo da visita e a pessoa escreveu ______.",
      "O cheiro mais forte que já senti numa ala hospitalar foi de ______.",
      "Na sala de cirurgia, o silêncio foi quebrado quando alguém gritou ______.",
      "O boletim médico do paciente famoso revelou que ele tinha ______.",
      "A visita ao hospital virou circo quando a família trouxe ______.",
      "O aviso na porta da enfermaria dizia: proibido entrar com ______.",
      "Todo plantonista de hospital tem uma história sobre ______ no elevador.",
      "O que mais irrita um enfermeiro de plantão é quando o paciente pede ______.",
      "Na recepção do hospital particular, cobraram uma taxa extra por ______.",
      "O exame de sangue voltou com um resultado bizarro apontando ______.",
      "Na ala psiquiátrica, o paciente mais calmo era o que falava sobre ______.",
      "O que nunca pode faltar num kit de primeiros socorros é ______.",
      "A ambulância chegou correndo por causa de ______.",
      "No raio-x apareceu algo que ninguém esperava: ______.",
      "A vizinha de quarto no hospital não parava de reclamar de ______.",
      "O médico residente aprendeu na marra que nunca deve ______.",
      "Durante a cirurgia, o anestesista comentou baixinho sobre ______.",
      "A sala de espera lotou depois que espalharam boato sobre ______.",
      "O prontuário médico mais engraçado que já vi mencionava ______.",
      "No berçário, as enfermeiras apostaram sobre qual bebê ia nascer parecido com ______.",
      "A dieta do hospital proibiu terminantemente ______.",
      "O paciente recém-operado insistiu em levantar da cama por causa de ______.",
      "Na sala de emergência, gritaram para trazer ______ com urgência.",
      "O laudo médico trouxe uma recomendação inusitada: evitar ______.",
      "Todo hospital tem aquele funcionário que esconde ______ no armário.",
      "A enfermaria virou motivo de piada depois que descobriram ______ escondido.",
      "O soro do paciente foi trocado às pressas por causa de ______.",
      "No corredor da maternidade, o pai desmaiou ao ouvir sobre ______.",
      "A camisola de hospital ficou famosa por causa de ______.",
      "O médico plantonista jura que já viu de tudo, inclusive ______.",
      "A campainha de emergência tocou sem parar por causa de ______.",
      "O paciente do apartamento VIP só reclamava da falta de ______.",
      "Na consulta de rotina, o médico ficou surpreso ao perguntar sobre ______.",
      "O hospital teve que chamar segurança depois que alguém trouxe ______.",
      "A fila do pronto-socorro parou tudo quando apareceu ______.",
      "No relatório de alta, o médico escreveu que o paciente teve alta por causa de ______."
    ]
  },
  {
    id: 'parquinho',
    label: 'Parquinho',
    questions: [
      "Na roda de mães do parquinho, o assunto do dia foi ______.",
      "O pai que ficou no banco do parquinho o tempo todo só falava de ______.",
      "A discussão mais acalorada do playground foi sobre quem trouxe ______.",
      "O grupo de WhatsApp das mães da escolinha bombou depois que alguém postou ______.",
      "Na hora do lanche coletivo, ninguém esperava que a mãe trouxesse ______.",
      "O zelador do parquinho jura que já viu de tudo, inclusive ______.",
      "A competição de quem tem o filho mais esperto virou vergonha depois de ______.",
      "No aniversário de criança no parquinho, o que mais deu o que falar foi ______.",
      "A vizinha fofoqueira do playground espalhou que o casal ali da esquina tinha ______.",
      "O balanço quebrou justamente na hora em que alguém tentou mostrar ______.",
      "Na reunião de pais, o assunto que ninguém esperava discutir foi ______.",
      "O pai coruja trouxe pro parquinho um equipamento que ninguém pediu: ______.",
      "A mãe do prédio ao lado ficou famosa no bairro por causa de ______.",
      "O escorregador ficou interditado depois que descobriram ______.",
      "Na disputa por quem organiza a festa junina da escolinha, rolou boato sobre ______.",
      "O grupo de pais decidiu banir do playground qualquer um que trouxesse ______.",
      "A caixa de areia virou assunto sério depois que acharam ______ escondido nela.",
      "No churrasco de confraternização das famílias, o climão começou quando alguém mencionou ______.",
      "A gangorra parou de funcionar bem na hora em que dois pais discutiam sobre ______.",
      "O condomínio proibiu o uso do parquinho depois do escândalo envolvendo ______.",
      "Na fila pra pegar as crianças, duas mães quase brigaram por causa de ______.",
      "O aviso novo na entrada do playground diz: proibido trazer ______.",
      "A avó que fica de olho nos netos contou pra todo mundo sobre ______.",
      "O grupo de pais do time de futebol infantil rachou depois de uma discussão sobre ______.",
      "Na live dos pais no Instagram, o comentário mais bizarro foi sobre ______.",
      "O parquinho virou point às escondidas depois que descobriram ______ ali de madrugada.",
      "A síndica colocou câmera nova no playground por causa de ______.",
      "Na roda de conversa dos pais, ninguém esperava a confissão sobre ______.",
      "O casal que sempre discute alto no parquinho tava brigando por causa de ______.",
      "A professora da escolinha levou um susto quando um pai apareceu com ______.",
      "No dia das crianças, o brinde mais estranho que distribuíram foi ______.",
      "A vizinha do playground jura que viu um pai fazendo ______ escondido.",
      "O grupo dos pais organizou uma vaquinha suspeita pra comprar ______.",
      "Na disputa de quem é o pai mais descolado, um deles apareceu com ______.",
      "O portão do parquinho emperrou bem na hora em que alguém tentava esconder ______.",
      "A reunião de condomínio virou climão quando debateram sobre ______ no playground.",
      "O pai que trabalha home office aproveitou o parquinho pra fazer ______.",
      "Na hora da soneca das crianças, os pais aproveitaram pra fofocar sobre ______.",
      "O grupo das mães decidiu criar uma regra nova contra ______ no playground.",
      "A campainha do prédio tocou sem parar porque alguém viu ______ no parquinho de madrugada."
    ]
  },
  {
    id: 'escola',
    label: 'Escola',
    questions: [
      "Na sala dos professores, o assunto mais comentado da semana foi ______.",
      "O diretor chamou os pais na escola por causa de ______.",
      "Na prova surpresa, a pergunta mais estranha foi sobre ______.",
      "O boletim voltou pra casa com uma anotação sobre ______.",
      "Na hora do recreio, rolou treta generalizada por causa de ______.",
      "O professor de educação física perdeu a paciência com ______.",
      "Na festa junina da escola, a barraca mais concorrida vendia ______.",
      "O bilhete que a escola mandou pros pais falava sobre ______.",
      "Na formatura, o discurso mais inesperado mencionou ______.",
      "O grêmio estudantil organizou uma campanha polêmica sobre ______.",
      "Na sala de aula, o professor confiscou ______ de um aluno.",
      "O cantinho da leitura foi interditado depois que acharam ______.",
      "Na reunião de pais e mestres, ninguém esperava ouvir sobre ______.",
      "O uniforme da escola ficou famoso depois que alguém bordou ______ nele.",
      "Na excursão escolar, o ônibus quase virou bagunça por causa de ______.",
      "O intervalo da escola virou assunto de grupo de pais depois de ______.",
      "Na apresentação de talentos, o número mais bizarro envolveu ______.",
      "O professor substituto levou um choque no primeiro dia ao ver ______.",
      "Na cantina da escola, o item mais vendido esse ano foi ______.",
      "O mural da escola foi pichado com uma frase sobre ______.",
      "Na hora cívica, o hino foi interrompido por causa de ______.",
      "O laboratório de ciências virou bagunça depois que um aluno trouxe ______.",
      "Na fila da merenda, a maior confusão foi sobre quem levou ______.",
      "O coordenador pedagógico teve que intervir por causa de ______.",
      "Na gincana da escola, a prova mais absurda pedia pra trazer ______.",
      "O quadro de avisos anunciou uma regra nova proibindo ______.",
      "Na sala de detenção, o motivo mais engraçado que já ouvi foi ______.",
      "O professor de história contou uma curiosidade sobre ______ que ninguém esqueceu.",
      "Na hora do intervalo, o pátio parou pra ver ______ acontecendo.",
      "O time de vôlei da escola comemorou a vitória trazendo ______.",
      "Na feira de ciências, o projeto mais criativo (e estranho) envolvia ______.",
      "O grupo de WhatsApp da turma bombou depois que alguém mandou ______.",
      "Na sala de informática, o professor pegou um aluno pesquisando ______.",
      "O uniforme sumiu do vestiário e apareceu no meio de ______.",
      "Na aula de artes, a obra mais polêmica retratava ______.",
      "O inspetor de alunos correu pelo corredor atrás de ______.",
      "Na semana cultural, a apresentação que mais chocou a plateia foi sobre ______.",
      "O aluno nota dez surpreendeu todo mundo ao confessar ______.",
      "Na roda de amigos do colégio, o segredo mais guardado era sobre ______.",
      "O sinal da escola tocou bem na hora em que todo mundo descobriu ______."
    ]
  },
  {
    id: 'faculdade',
    label: 'Faculdade',
    questions: [
      "Na resenha da faculdade, o assunto que bombou foi ______.",
      "O professor cancelou a prova depois de descobrir ______.",
      "Na república estudantil, a regra mais respeitada era nunca mexer em ______.",
      "O trabalho em grupo desandou quando alguém sugeriu ______.",
      "Na calourada, o trote mais absurdo envolveu ______.",
      "O diretório acadêmico organizou uma festa que ficou famosa por causa de ______.",
      "Na apresentação de TCC, a banca ficou em choque com ______.",
      "O estágio obrigatório virou pesadelo por causa de ______.",
      "Na biblioteca da faculdade, pegaram um aluno fazendo ______ escondido.",
      "O grupo do WhatsApp da turma explodiu depois que postaram ______.",
      "Na prova final, o cola mais criativo que já vi tinha ______ escrito.",
      "O professor titular é famoso na faculdade por causa de ______.",
      "Na festa da atlética, rolou treta generalizada envolvendo ______.",
      "O currículo do aluno mais gabaritado da turma incluía ______.",
      "Na sala de aula, o debate mais acalorado do semestre foi sobre ______.",
      "O laboratório da faculdade foi interditado depois que descobriram ______.",
      "Na formatura, o paraninfo escolhido surpreendeu todo mundo por causa de ______.",
      "O intercâmbio acadêmico rendeu uma história inesquecível sobre ______.",
      "Na resenha de sexta, o item que nunca pode faltar é ______.",
      "O monitor da disciplina foi flagrado fazendo ______ durante a aula.",
      "Na moradia estudantil, a regra número um era nunca esconder ______.",
      "O grupo de pesquisa publicou um artigo bizarro sobre ______.",
      "Na apresentação de seminário, o slide mais constrangedor mostrava ______.",
      "O aluno bolsista revelou o segredo por trás de ______.",
      "Na sala do centro acadêmico, guardavam escondido ______.",
      "O professor recém-contratado ficou famoso por causa de ______.",
      "Na formatura da turma, o brinde mais absurdo foi feito com ______.",
      "O estágio de verão virou meme depois que alguém postou ______.",
      "Na disciplina de ética, discutiram um caso real envolvendo ______.",
      "O grêmio universitário organizou uma campanha polêmica sobre ______.",
      "Na república, a lista de compras coletiva sempre incluía ______.",
      "O professor visitante contou uma história inacreditável sobre ______.",
      "Na prova oral, o examinador ficou sem reação ao ouvir sobre ______.",
      "O aluno mais popular do curso ficou famoso por causa de ______.",
      "Na semana de recepção dos calouros, a dinâmica mais estranha envolveu ______.",
      "O trabalho de conclusão de curso quase foi reprovado por causa de ______.",
      "Na sala dos professores, comentaram baixinho sobre ______.",
      "O aplicativo de caronas da faculdade ficou famoso depois de ______.",
      "Na festa de encerramento do semestre, o brinde surpresa foi ______.",
      "O coordenador do curso teve que se explicar sobre ______."
    ]
  },
  {
    id: 'casa',
    label: 'Em Casa',
    questions: [
      "Na reunião de família, o assunto que ninguém queria tocar foi ______.",
      "A gaveta trancada do armário escondia ______.",
      "No almoço de domingo, a discussão começou por causa de ______.",
      "A empregada encontrou ______ embaixo da cama.",
      "No grupo de família do WhatsApp, a bomba da semana foi ______.",
      "A geladeira estava vazia, só tinha ______.",
      "No quintal, o vizinho jura que viu ______ pendurado no varal.",
      "A sogra chegou de surpresa e encontrou ______ na sala.",
      "No aniversário de casamento, o presente mais estranho foi ______.",
      "A faxina de fim de ano revelou ______ escondido no sótão.",
      "No jantar em família, ninguém esperava que alguém trouxesse ______ à mesa.",
      "A lista de compras do mês incluía, sem explicação, ______.",
      "No churrasco de família, o climão começou quando surgiu ______.",
      "A caixa de lembranças da vovó guardava ______.",
      "No quarto dos fundos, encontraram uma coleção secreta de ______.",
      "A conta de luz veio alta esse mês por causa de ______.",
      "No porta-retrato da sala, tinha uma foto de ______ que ninguém explicou.",
      "A discussão de casal mais clássica é sempre sobre ______.",
      "No Natal em família, o presente que causou climão foi ______.",
      "A vizinha bisbilhoteira contou pro prédio inteiro sobre ______.",
      "No armário do banheiro, tinha escondido ______.",
      "A reforma da casa parou por causa de uma descoberta chocante: ______.",
      "No grupo da família, a tia mandou uma mensagem confusa sobre ______.",
      "A mudança pra casa nova revelou ______ que o antigo dono deixou.",
      "No fundo do quintal, o cachorro desenterrou ______.",
      "A sala de estar virou bagunça depois da festa surpresa com ______.",
      "No jogo de tabuleiro em família, a briga começou por causa de ______.",
      "A esposa descobriu, no bolso da calça, ______.",
      "No porão da casa, tinha uma caixa lacrada só escrito ______.",
      "A reunião de condomínio virou climão por causa de ______.",
      "No churrasco de aniversário, o tio bêbado contou sobre ______.",
      "A troca de fraldas do bebê revelou um susto: ______.",
      "No feriado prolongado, a família toda brigou por causa de ______.",
      "A sogra deixou um bilhete na geladeira falando de ______.",
      "No aniversário de 15 anos, o presente mais bizarro veio dentro de ______.",
      "A empregada pediu demissão depois de encontrar ______ na lavanderia.",
      "No jantar de reveillon, o brinde mais estranho foi feito com ______.",
      "A vovó contou, sem pudor nenhum, a história de quando ______.",
      "No quintal do vizinho, ninguém sabia explicar o barulho de ______.",
      "A herança da família causou briga por causa de ______."
    ]
  },
  {
    id: 'igreja',
    label: 'Igreja',
    questions: [
      "No meio do culto, o pastor parou o sermão por causa de ______.",
      "A irmã da terceira fileira desmaiou ao ver ______.",
      "Na escola bíblica infantil, a tia explicou de um jeito estranho sobre ______.",
      "No coral da igreja, a treta começou porque alguém queria cantar sobre ______.",
      "Na oferta do domingo, o pastor pediu especificamente por ______.",
      "O casamento na igreja parou quando alguém gritou sobre ______.",
      "Na reunião de jovens, o assunto proibido da noite foi ______.",
      "O diácono foi flagrado escondendo ______ atrás do altar.",
      "Na vigília de oração, ninguém esperava um pedido tão específico: ______.",
      "O grupo de WhatsApp da igreja bombou depois que postaram ______.",
      "Na procissão, o andor quase caiu por causa de ______.",
      "A irmã fofoqueira contou pra congregação inteira sobre ______.",
      "No batizado, o bebê chorou desesperado assim que viu ______.",
      "Na feira beneficente da igreja, o item mais vendido foi ______.",
      "O pastor visitante ficou famoso na cidade por causa de ______.",
      "Na confissão, o segredo mais chocante que já ouviram foi sobre ______.",
      "O casamento comunitário virou assunto da cidade por causa de ______.",
      "Na reunião de líderes, decidiram proibir ______ nas dependências da igreja.",
      "O grupo de louvor cancelou o ensaio depois que descobriram ______.",
      "Na festa de aniversário da igreja, o bolo veio decorado com ______.",
      "A irmã responsável pela cozinha comunitária escondia ______ na despensa.",
      "No retiro espiritual, o momento mais surreal foi quando apareceu ______.",
      "O sistema de som falhou bem na hora do anúncio sobre ______.",
      "Na campanha do agasalho, doaram, sem querer, ______.",
      "O casal mais tradicional da igreja foi flagrado fazendo ______.",
      "Na escola dominical, uma criança perguntou algo que deixou todo mundo sem resposta: ______.",
      "O culto de gratidão virou climão depois que alguém testemunhou sobre ______.",
      "Na sala dos fundos da igreja, guardavam escondido ______.",
      "O pastor pediu silêncio total antes de anunciar ______.",
      "Na quermesse, a barraca mais concorrida vendia ______.",
      "O microfone ficou aberto sem querer e todo mundo ouviu sobre ______.",
      "Na reunião de casais, a dinâmica mais constrangedora envolveu ______.",
      "O sacristão contou, baixinho, o segredo por trás de ______.",
      "Na celebração de aniversário da igreja, trouxeram de surpresa ______.",
      "O grupo de intercessão orou especificamente por causa de ______.",
      "Na saída do culto, o comentário mais absurdo foi sobre ______.",
      "O evento beneficente arrecadou fundos vendendo ______.",
      "Na reforma do templo, encontraram escondido atrás da parede ______.",
      "O anúncio no boletim dominical mencionava, sem explicação, ______.",
      "Na despedida do pastor, o presente de gratidão foi ______."
    ]
  },
  {
    id: 'terreiro',
    label: 'Terreiro',
    questions: [
      "No terreiro, a gira parou por um instante quando chegou ______.",
      "Na cozinha do terreiro, o cheiro mais gostoso da festa vinha de ______.",
      "Na roda de axé, todo mundo ficou surpreso ao ver ______.",
      "No dia da festa de Iemanjá, alguém apareceu trazendo ______.",
      "Na sala de consulta, a mãe de santo perguntou logo de cara sobre ______.",
      "No salão do terreiro, a decoração mais chamativa daquele ano foi ______.",
      "Depois da gira, o assunto que rolou solto na cozinha comunitária foi ______.",
      "Na roda de conversa antes da festa, contaram a história de quando ______.",
      "No terreiro, ninguém esperava que a oferenda incluísse ______.",
      "Na noite de festa, o ponto de comida mais concorrido foi o que tinha ______.",
      "No batuque, o tambor parou de repente por causa de ______.",
      "Na entrada do terreiro, deixaram um aviso simpático sobre ______.",
      "Na roda dos mais velhos, contaram um causo inesquecível sobre ______.",
      "No dia de limpeza do terreiro, encontraram escondido ______.",
      "Na festa de aniversário do terreiro, o bolo comunitário veio com ______.",
      "Na cozinha, a disputa da noite foi sobre quem fez o melhor ______.",
      "No salão de festas do terreiro, a decoração surpreendeu todo mundo com ______.",
      "Na despedida da festa, o presente simbólico distribuído foi ______.",
      "No grupo de WhatsApp da casa, a novidade da semana foi ______.",
      "Na roda de visitantes, a pergunta mais engraçada foi sobre ______.",
      "Depois da festa, a limpeza do salão revelou ______ esquecido num canto.",
      "Na feira de artesanato do terreiro, o item mais vendido foi ______.",
      "No dia de arrumação, alguém trouxe de surpresa ______ pra ajudar.",
      "Na cozinha comunitária, a receita secreta da casa levava ______.",
      "Na confraternização de fim de ano, o presente amigo oculto mais engraçado foi ______.",
      "Na roda de história, contaram sobre a vez em que ______ aconteceu na festa.",
      "No salão, a música que mais animou a galera falava sobre ______.",
      "Na organização da festa, a comissão decidiu incluir ______ no cardápio.",
      "No fim da celebração, o agradecimento especial foi por causa de ______.",
      "Na feira beneficente, arrecadaram fundos vendendo ______.",
      "Na roda de conversa da tarde, o boato do bairro era sobre ______.",
      "No dia de doação de cestas básicas, alguém contribuiu com ______.",
      "Na cozinha, a discussão mais engraçada foi sobre o tempero de ______.",
      "No salão decorado pra festa, o detalhe que mais chamou atenção foi ______.",
      "Na roda dos jovens da casa, o assunto do momento era ______.",
      "Depois da celebração, o comentário mais engraçado da noite foi sobre ______.",
      "Na organização da confraternização, decidiram surpreender todo mundo com ______.",
      "No bazar beneficente, o item mais disputado da tarde foi ______.",
      "Na despedida de ano, o brinde especial da casa foi feito com ______.",
      "Na roda de agradecimento, todo mundo comentou sobre ______."
    ]
  },
  {
    id: 'praia',
    label: 'Praia',
    questions: [
      "Na praia lotada, todo mundo virou pra ver ______ passando.",
      "O guarda-vidas correu quando alguém gritou por causa de ______.",
      "Na barraca de praia, o item mais pedido do dia foi ______.",
      "O vendedor ambulante ficou famoso na praia por vender ______.",
      "Na areia, a briga por espaço começou por causa de ______.",
      "O quiosque mais concorrido da orla vendia ______.",
      "Na virada de ano na praia, o brinde mais estranho foi feito com ______.",
      "O jogo de futevôlei parou quando apareceu ______ no meio da quadra.",
      "Na barraca ao lado, o grupo estava comemorando por causa de ______.",
      "O mar devolveu na areia algo que ninguém esperava: ______.",
      "Na praia de nudismo, o comentário mais engraçado foi sobre ______.",
      "O vendedor de picolé quase caiu ao ver ______ na areia.",
      "Na roda de amigos, a história mais absurda contada na praia foi sobre ______.",
      "O pôr do sol foi interrompido quando alguém trouxe ______.",
      "Na fila do banheiro público da praia, rolou treta por causa de ______.",
      "O barraqueiro proibiu terminantemente que trouxessem ______ pra barraca.",
      "Na praia deserta, o casal foi flagrado fazendo ______.",
      "O caiaque virou no meio do mar por causa de ______.",
      "Na feira de artesanato da orla, o item mais estranho à venda era ______.",
      "O carro de som da praia anunciou, sem explicação, ______.",
      "Na disputa de vôlei de praia, o climão começou por causa de ______.",
      "O quiosque decidiu criar um drink novo chamado ______.",
      "Na praia do nudismo, a placa avisava: proibido ______.",
      "O jangadeiro contou uma história inacreditável sobre ______.",
      "Na temporada de verão, o bar da praia ficou famoso por causa de ______.",
      "O grupo de amigos alugou uma casa na praia só pra fazer ______.",
      "Na disputa do castelo de areia mais bonito, o vencedor usou ______.",
      "O salva-vidas resgatou um turista que tinha ido nadar por causa de ______.",
      "Na barraca vizinha, discutiam alto sobre quem trouxe ______.",
      "O sol forte não impediu ninguém de continuar fazendo ______ na areia.",
      "Na feira noturna da orla, o show mais inesperado envolveu ______.",
      "O trailer de comida na praia ficou famoso pelo seu ______ especial.",
      "Na canoagem em grupo, alguém caiu na água por causa de ______.",
      "O réveillon na praia terminou com todo mundo comentando sobre ______.",
      "Na disputa por sombra na areia, o climão foi por causa de ______.",
      "O grupo de surfistas ficou famoso na praia por causa de ______.",
      "Na fila do quiosque, o pedido mais estranho da tarde foi ______.",
      "O carro estacionado na orla foi flagrado com ______ dentro.",
      "Na praia lotada de feriado, o barulho que mais incomodou foi ______.",
      "O pescador contou que já viu de tudo no mar, inclusive ______."
    ]
  },
  {
    id: 'metro',
    label: 'Metrô',
    questions: [
      "No metrô lotado, ninguém esperava ver ______ dentro do vagão.",
      "A voz do alto-falante anunciou um atraso por causa de ______.",
      "No horário de pico, a maior confusão da plataforma foi por causa de ______.",
      "O passageiro do banco ao lado começou a falar sozinho sobre ______.",
      "Na catraca do metrô, alguém tentou passar escondendo ______.",
      "O vagão lotado parou de repente por causa de ______.",
      "Na plataforma, o vendedor ambulante estava oferecendo ______.",
      "O funcionário da estação teve que chamar segurança por causa de ______.",
      "No metrô da madrugada, o passageiro mais estranho carregava ______.",
      "A porta do vagão fechou bem na hora em que alguém gritava sobre ______.",
      "No elevador da estação, ficaram presos por causa de ______.",
      "O grafite mais famoso da estação retratava ______.",
      "Na roleta de entrada, travou justamente quando alguém tentava levar ______.",
      "O passageiro distraído esqueceu ______ dentro do vagão.",
      "Na fila do bilhete, a discussão começou por causa de ______.",
      "O músico que toca na estação ficou famoso por cantar sobre ______.",
      "No vagão feminino, rolou climão por causa de ______.",
      "A estação foi interditada temporariamente por causa de ______.",
      "No metrô, o cheiro mais forte do vagão vinha de ______.",
      "O passageiro apertado no rush comentou baixinho sobre ______.",
      "Na escada rolante, alguém deixou cair ______ e virou zoeira geral.",
      "O guarda da estação recolheu, sem explicação, ______ de um passageiro.",
      "No banco reservado, a discussão foi sobre quem tinha mais direito a ______.",
      "A campainha da porta tocou insistente por causa de ______.",
      "No túnel escuro entre estações, alguém jurou ter visto ______.",
      "O anúncio de emergência pediu calma por causa de ______.",
      "Na saída da estação, um grupo estava vendendo ______ escondido.",
      "O passageiro chorou desesperadamente ao perder ______ no metrô.",
      "Na plataforma lotada, todo mundo empurrou por causa de ______.",
      "O trem parou entre estações e o clima ficou tenso por causa de ______.",
      "No mapa da linha, alguém rabiscou uma piada sobre ______.",
      "A bilheteria fechou mais cedo por causa de ______.",
      "No vagão silencioso, o barulho mais irritante veio de ______.",
      "O passageiro do celular alto estava falando sem parar sobre ______.",
      "Na hora do rush, um grupo se organizou pra vender ______ escondido dos fiscais.",
      "O elevador quebrado da estação virou motivo de reclamação sobre ______.",
      "No fim de linha, o funcionário encontrou ______ esquecido no último vagão.",
      "A fila da bilheteria rendeu uma discussão generalizada sobre ______.",
      "No metrô lotado, o cheiro de perfume forte era de alguém carregando ______.",
      "A estação mais movimentada da cidade ficou famosa por causa de ______."
    ]
  },
  {
    id: 'feira',
    label: 'Feira',
    questions: [
      "Na feira livre, o barraqueiro mais popular vendia ______.",
      "A discussão de preço na banca de frutas começou por causa de ______.",
      "Na feira, a fila mais comprida da manhã era pra comprar ______.",
      "O feirante gritava anunciando promoção de ______.",
      "Na roda de conversa entre os feirantes, o assunto do dia era ______.",
      "A cliente reclamona da feira sempre discute sobre ______.",
      "Na banca de peixe, o cheiro mais forte da manhã vinha de ______.",
      "O carrinho de compras quebrou no meio da feira carregando ______.",
      "Na feira orgânica, o item mais caro (e estranho) era ______.",
      "O feirante mais antigo do bairro contou uma história sobre ______.",
      "Na disputa por espaço na barraca, o climão foi por causa de ______.",
      "A senhora que sempre pechincha levou de graça ______.",
      "Na feira noturna, o food truck mais concorrido vendia ______.",
      "O barraqueiro de tempero ficou famoso na região por causa de ______.",
      "Na feira de domingo, a maior fila da manhã era pra experimentar ______.",
      "O ambulante que passa vendendo ______ é conhecido de todo mundo.",
      "Na banca de flores, o pedido mais estranho da semana foi ______.",
      "O feirante contou que já viu de tudo, inclusive ______ sendo vendido escondido.",
      "Na feira de artesanato, o item mais bizarro à venda era ______.",
      "A cliente distraída esqueceu ______ em cima da banca.",
      "Na roda de fofoca das feirantes, o assunto mais comentado foi ______.",
      "O caminhão de entrega chegou atrasado por causa de ______.",
      "Na feira do produtor, o item que mais vendeu esse mês foi ______.",
      "O feirante mais gente boa da região sempre dá de brinde ______.",
      "Na banca de queijos, o cliente pediu pra provar antes de comprar ______.",
      "A discussão na feira sobre quem chegou primeiro na fila envolveu ______.",
      "O food truck novo da feira ficou famoso pelo seu ______ especial.",
      "Na feira de troca, alguém trocou o carro por ______.",
      "O guarda municipal teve que intervir na feira por causa de ______.",
      "Na banca de temperos, o cheiro mais forte da manhã era de ______.",
      "A senhora do bairro compra toda semana, sem falta, ______.",
      "Na feira, o vendedor de CD pirata também vendia escondido ______.",
      "O motorista do caminhão de hortifruti reclamou de ______ atrapalhando a entrega.",
      "Na feira de rua, o show ambulante fez todo mundo parar pra ver ______.",
      "O barraqueiro mais rabugento nunca aceita reclamação sobre ______.",
      "Na feira de sábado, o item que sumiu mais rápido das bancas foi ______.",
      "A vendedora de doces caseiros ficou famosa por causa de ______.",
      "Na negociação de última hora, o feirante topou trocar por ______.",
      "O cheiro de café fresco da feira se misturava com o de ______.",
      "Na feira, a maior confusão do dia foi por causa da fila pra comprar ______."
    ]
  },
  {
    id: 'rua',
    label: 'Rua',
    questions: [
      "Na esquina do bairro, todo mundo comentava sobre ______.",
      "O carro parou no meio da rua por causa de ______.",
      "Na calçada, o vizinho jurou ter visto ______ passando de madrugada.",
      "O ambulante que vende picolé na rua ficou famoso por causa de ______.",
      "Na rua sem saída, o barulho que mais incomodava os moradores era ______.",
      "O poste de luz quebrado virou assunto do grupo de WhatsApp por causa de ______.",
      "Na esquina do bar, a treta começou por causa de ______.",
      "O carteiro contou que já viu de tudo nas ruas, inclusive ______.",
      "Na rua de terra, o buraco maior escondia ______.",
      "O guarda de trânsito parou o carro por causa de ______.",
      "Na calçada estreita, a briga por espaço foi por causa de ______.",
      "O grafite novo na parede da esquina retratava ______.",
      "Na rua do comércio, a loja mais visitada vendia ______.",
      "O vizinho barulhento é famoso na rua por causa de ______.",
      "Na madrugada, o barulho estranho vinha lá da rua de trás por causa de ______.",
      "O carro de som passou anunciando, sem explicação, ______.",
      "Na feira de rua improvisada, o item mais vendido foi ______.",
      "O motoboy quase caiu da moto desviando de ______.",
      "Na rua movimentada, o engarrafamento foi por causa de ______.",
      "O mendigo da esquina sempre pede, educadamente, ______.",
      "Na calçada da padaria, a fila da manhã só falava sobre ______.",
      "O buraco na rua virou piscina depois da chuva e alguém jogou ______ dentro.",
      "Na rua do bairro, o carro estacionado errado tinha ______ visível pela janela.",
      "O flanelinha da esquina cobra caro, mas garante cuidar de ______.",
      "Na esquina, o grupo de amigos ficou até tarde discutindo sobre ______.",
      "O poste virou ponto de referência depois que colaram cartaz sobre ______.",
      "Na rua deserta à noite, o único som era de ______.",
      "O carro alugado quebrou no meio da rua com ______ no banco de trás.",
      "Na calçada, o cachorro do vizinho fugiu correndo atrás de ______.",
      "O bloco de carnaval de rua ficou famoso por causa de ______.",
      "Na rua principal, o comércio fechou mais cedo por causa de ______.",
      "O caminhão de mudança bloqueou a rua carregando ______.",
      "Na esquina do colégio, os pais discutiam sobre ______.",
      "O muro pichado da rua tinha escrito ______ em letras gigantes.",
      "Na rua de pedestres, o artista de rua chamou atenção fazendo ______.",
      "O carro de polícia parou na esquina por causa de ______.",
      "Na calçada molhada, alguém escorregou segurando ______.",
      "O vendedor de rua foi embora correndo depois que viu ______.",
      "Na disputa por vaga de garagem na rua, o climão foi por causa de ______.",
      "O bairro inteiro comentou, por dias, sobre ______ que apareceu na rua."
    ]
  },
  {
    id: 'futebol',
    label: 'Campo de Futebol',
    questions: [
      "No campo do bairro, a pelada de domingo parou por causa de ______.",
      "O juiz amador marcou pênalti duvidoso e a torcida gritou sobre ______.",
      "No vestiário, o técnico deu um discurso inesquecível sobre ______.",
      "Na arquibancada, a torcida organizada trouxe uma faixa escrita ______.",
      "No intervalo do jogo, o comentário mais absurdo foi sobre ______.",
      "O goleiro amador jura que só tomou o gol por causa de ______.",
      "Na final do campeonato de várzea, o climão começou por causa de ______.",
      "O gramado do campo estava um caos por causa de ______.",
      "Na disputa de pênaltis, a torcida ficou em silêncio esperando ______.",
      "O time reserva comemorou o empate trazendo ______ pro vestiário.",
      "Na lateral do campo, o cambista estava vendendo ______ escondido.",
      "O narrador amador do campeonato de bairro comentou sobre ______ ao vivo.",
      "Na confraternização depois do jogo, o churrasco ficou famoso por causa de ______.",
      "O uniforme do time do bairro foi trocado de última hora por causa de ______.",
      "Na disputa acirrada, o técnico tirou o jogador de campo por causa de ______.",
      "O campo alagou de chuva e ainda assim rolou o jogo por causa de ______.",
      "Na arquibancada de madeira, a torcida apostou uma rodada de ______.",
      "O juiz expulsou um jogador depois que ele reclamou sobre ______.",
      "Na quadra society, a pelada de sexta-feira sempre termina com ______.",
      "O time de várzea patrocinado pelo bar ganhou de presente ______.",
      "Na comemoração do gol, o jogador tirou a camisa mostrando ______.",
      "O vestiário do time visitante virou assunto depois que descobriram ______.",
      "Na disputa pelo título amador, a torcida rival provocou com ______.",
      "O gramado sintético do campo novo custou caro por causa de ______.",
      "Na cobrança de falta, a barreira se formou torta por causa de ______.",
      "O árbitro auxiliar levantou a bandeirinha alertando sobre ______.",
      "Na roda de resenha pós-jogo, o assunto mais comentado foi ______.",
      "O time amador contratou um reforço famoso por causa de ______.",
      "Na disputa pela taça, o presidente do clube prometeu ______ pro time campeão.",
      "O bar ao lado do campo lotou no dia da final vendendo ______.",
      "Na cobrança de escanteio, a confusão começou por causa de ______.",
      "O treino de sábado foi cancelado de última hora por causa de ______.",
      "Na disputa de pênaltis decisiva, o goleiro comemorou segurando ______.",
      "O time feminino do bairro ficou famoso na cidade por causa de ______.",
      "Na saída do campo, a torcida discutia acaloradamente sobre ______.",
      "O uniforme numerado sumiu do vestiário junto com ______.",
      "Na quadra de futsal, a pelada da firma sempre rende histórias sobre ______.",
      "O técnico do time de várzea jura nunca ter visto algo igual a ______.",
      "Na comemoração do campeonato, o troféu foi erguido junto com ______.",
      "O campinho de terra do bairro ficou famoso na cidade por causa de ______."
    ]
  }
];

export const ALL_QUESTIONS: string[] = QUESTION_CATEGORIES.flatMap(c => c.questions);
