export const ENGLISH_QUESTIONS: string[] = [
  "At the neighborhood barbecue, the most awkward moment was caused by ___.",
  "Never invite your boss to a party if you plan on bringing ___.",
  "The secret ingredient in grandma's famous stew was actually ___.",
  "I knew my date was going terribly wrong when they pulled out ___.",
  "What finally ruined the royal family dinner? ___.",
  "My New Year's resolution was simple: avoid ___ at all costs.",
  "The real reason aliens refuse to visit Earth is ___.",
  "In my past life, I was probably ___.",
  "The only thing worse than waking up on Monday is ___.",
  "What is the CEO secretly hiding in the company basement? ___.",
  "For my next trick, I will make ___ disappear completely!",
  "The headline tomorrow morning will read: 'Local man arrested for ___'.",
  "Nothing brings a family together quite like ___.",
  "During the flight turbulence, the pilot calmly whispered over the intercom: 'Please beware of ___'.",
  "The worst possible gift for a 5-year-old birthday party is ___.",
  "I went to therapy and my therapist recommended ___.",
  "What really caused the fall of the Roman Empire? ___.",
  "My secret superpower is the ability to summon ___ whenever I sneeze.",
  "When the police knocked on the door, I quickly hid ___ under the bed.",
  "The biggest red flag on any dating profile is definitely ___.",
  "The secret to a 50-year happy marriage is simple: lots of ___.",
  "What was hidden inside the pirate's treasure chest? ___.",
  "The doctor looked at my X-ray and said: 'Congratulations, you have ___.'",
  "School never prepared me for the harsh reality of ___.",
  "If loving ___ is wrong, then I don't want to be right.",
  "The VIP lounge strictly prohibits bringing ___.",
  "What's keeping me awake at 3 AM? ___.",
  "The ultimate secret to becoming a billionaire is ___.",
  "My dog barked at the closet door until I opened it and found ___.",
  "The main event at the circus was canceled due to ___.",
  "Before I die, I want to experience ___ just one more time.",
  "The next viral TikTok dance will be called 'The ___'.",
  "Instead of a wedding cake, the bride insisted on ___.",
  "What did the fortune teller see in my crystal ball? ___.",
  "The police found no evidence at the crime scene except for ___.",
  "My GPS took a wrong turn and directed me straight into ___.",
  "What is the number one cause of workplace arguments? ___.",
  "The elevator broke down between floors, leaving us trapped with ___.",
  "A romantic candlelit dinner is ruined immediately if you mention ___.",
  "What really happened on Area 51? A massive experiment with ___.",
  "___: the only thing 100% guaranteed to cure a hangover.",
  "I accidentally sent an email to the entire company containing ___.",
  "The new superhero movie features a hero whose only weakness is ___.",
  "Why did the teacher suddenly quit in the middle of class? Because of ___.",
  "My bank account is currently screaming at me because of ___.",
  "The secret recipe for true happiness is 90% love and 10% ___.",
  "What was the real reason behind Noah's Ark? To escape from ___.",
  "The worst thing to hear during surgery: 'Oops, where is ___?'",
  "I joined a gym exclusively to get away from ___.",
  "If aliens landed right now, the first thing I would show them is ___."
];

export const ENGLISH_ANSWERS: string[] = [
  "an emotional support raccoon",
  "my bank account crying softly",
  "that awkward 8-minute voice memo",
  "an unsolicited 3 AM text from my ex",
  "pure chaotic energy",
  "a suspiciously loud fart in church",
  "an aggressively enthusiastic gym coach",
  "pretending to understand quantum physics",
  "a dramatic exit through the window",
  "blaming everything on mercury retrograde",
  "a terrifyingly detailed horoscope",
  "drinking tap water in a fancy glass",
  "an overpriced yoga retreat",
  "forgetting someone's name mid-conversation",
  "a PowerPoint presentation about my feelings",
  "the awkward silence after 'we need to talk'",
  "stealing mini hotel shampoos like a villain",
  "a life coach who lives with his parents",
  "unfiltered gossip from the neighbor",
  "my browser history from 2 AM",
  "a dramatic slow-motion slap",
  "sweatpants with fancy sunglasses",
  "pretending to laugh at a terrible joke",
  "a coupon that expired three years ago",
  "calling the teacher 'Mom' by accident",
  "an overly competitive Monopoly player",
  "eating an entire pizza alone in bed",
  "a fake British accent in emergencies",
  "a suspicious package from wish.com",
  "spilling hot coffee directly onto my lap",
  "dancing terribly at a wedding reception",
  "a dramatic karaoke breakdown",
  "replying 'you too' when the waiter says 'enjoy your meal'",
  "an inflatable dinosaur costume",
  "a passive-aggressive thumbs-up emoji",
  "a self-help book written by a cat",
  "pretending to be busy on a fake phone call",
  "an absurd amount of cheese",
  "walking into a spiderweb at full speed",
  "a dramatic monologue in the shower",
  "a cursed family group chat",
  "crying during a financial spreadsheet review",
  "a fake mustache falling into the soup",
  "running away from all my adult responsibilities",
  "a dog judging your life choices",
  "the fear of answering an unknown phone call",
  "a suspiciously confident toddler",
  "putting off a 2-minute task for 3 weeks",
  "ordering delivery while standing in the kitchen",
  "a deeply disturbing fortune cookie"
];
