import { ALL_QUESTIONS } from './questionsData.js';

export function contarEspacos(texto: string): number {
  return (texto.match(/_{3,}/g) || []).length || 1;
}

export const FALLBACK_PERGUNTAS = ALL_QUESTIONS.map((texto) => ({
  texto,
  espacos: contarEspacos(texto),
}));

export const FALLBACK_RESPOSTAS: string[] = [
  'um motoboy com fé em Deus',
  'a vergonha alheia da família toda',
  'aquele silêncio constrangedor',
  'meu cartão de crédito chorando baixinho',
  'a vizinha fofoqueira do prédio',
  'um pastor cobrando dízimo em dobro',
  'meu ex me chamando às 2 da manhã',
  'a fila do INSS às 5 da manhã',
  'um pix errado de R$ 3.000',
  'a playlist secreta do tio no churrasco',
  'aquele áudio de 8 minutos que ninguém ouviu',
  'o cheiro de churrasco vindo do vizinho',
  'uma crise existencial no meio do rodízio',
  'o grupo da família no zap às 6h',
  'um santinho de político puxando conversa',
  'a promoção que só tem letra miúda',
  'meu horóscopo mentindo descaradamente',
  'um influenciador vendendo curso de nada',
  'a régua 22 do cabeleireiro',
  'o silêncio depois do "a gente precisa conversar"',
  'uma sogra com superpoderes de fofoca',
  'o boleto vencido há três meses',
  'aquele beijo técnico no Carnaval',
  'um chinelo voando com precisão cirúrgica',
  'a fé cega no cartão de crédito',
  'meu joelho estalando igual pipoca',
  'o WhatsApp da empresa fingindo ser urgente',
  'uma primeira comunhão regada a cerveja',
  'o tio que sabe tudo de política',
  'a vergonha de dar "oi" pra pessoa errada',
  'um exorcismo mal ensaiado',
  'a fila do banco que não anda',
  'meu currículo mentindo sobre Excel',
  'um bafo de cebola em plena entrevista',
  'a ressaca moral de domingo de manhã',
  'um professor particular de sedução',
  'a raiva de perder o ônibus por 2 segundos',
  'um pastor cobrando PIX no culto',
  'aquele abraço que dura tempo demais',
  'a saideira que virou madrugada inteira',
  'um cupido desempregado',
  'a fofoca que rendeu três novelas',
  'meu estagiário fingindo que entendeu',
  'um sermão de duas horas sobre nada',
  'a vergonha de rir no funeral errado',
  'um paçoquinha filosofando na roda de amigos',
  'o Uber cancelando na sua cara',
  'uma multa de trânsito por excesso de charme',
  'a promessa de malhar segunda-feira',
  'um exorcista freelancer',
  'a fila do posto de saúde às 4 da manhã',
  'meu quinto café do dia me julgando',
  'um bêbado declarando amor eterno',
  'a vergonha de cantar desafinado no chuveiro',
  'aquele stalker discreto do Instagram',
  'um pastor com Ferrari importada',
  'a saudade que só aparece à meia-noite',
  'um chefe que confunde humildade com humilhação',
  'meu terapeuta anotando tudo calado',
  'a bênção que veio em forma de boleto',
  'um cunhado emprestando dinheiro sem devolver',
  'aquele "kkk" seco de quem tá puto',
  'a coragem que só vem depois da terceira cerveja',
  'um karaokê que virou tragédia grega',
  'a saudação constrangedora no elevador',
  'meu Wi-Fi caindo no pior momento possível',
  'um vizinho que reforma a casa às 7h de domingo',
  'a fé inabalável de quem aposta na Mega-Sena',
  'um crush que só dá bom dia',
  'a vergonha de escorregar na igreja lotada',
  'meu álibi furado igual peneira',
  'um professor de ioga estressado',
  'a raiva de descobrir que era spam',
  'aquele parente que só aparece pra pedir favor',
  'um político prometendo emprego pra todo mundo',
  'a cara de paisagem quando alguém te chama pra ajudar a mudar',
  'um amigo que some quando a conta chega',
  'a autoestima depois de três taças de vinho',
  'meu chefe achando que WhatsApp é hora extra',
  'um casamento que durou menos que o buffet',
  'a fila do caixa eletrônico dia 5',
  'um evangélico discutindo futebol',
  'aquele oi visualizado sem resposta',
  'a vergonha de tropeçar no tapete vermelho da vida',
  'um vidente cobrando parcelado',
  'meu joelho avisando a mudança de tempo',
  'a saudade que aperta no fim de semana',
  'um sogro competindo no churrasco',
  'a fé de quem confia no motorista de aplicativo',
  'aquele grupo da faculdade que virou cemitério',
  'um padre comentando a novela das 9',
  'a vergonha de arrotar numa reunião importante',
  'meu orgulho falando mais alto que a razão',
  'um tio zap desmentindo cientista',
  'a raiva de perder o joguinho pro sobrinho',
  'um flerte capenga na academia',
  'a coragem líquida de sexta-feira',
  'meu banco cobrando taxa por respirar',
  'um exorcismo com playlist de forró',
  'a vergonha de dar risada no momento errado',
  'um chefe chamando reunião às 18h',
  'a fila do supermercado no dia do pagamento',
  'meu horóscopo culpando Mercúrio de novo',
  'um pastor vendendo água benta em dose dupla',
  'a saudade que vira stalker no Instagram',
  'um professor que confunde nota com vingança',
  'a vergonha de cair no meio da pista de dança',
  'meu ex aparecendo nos stories de todo mundo',
  'um cupido de plantão no grupo da família',
  'a fé em dieta que começa segunda que vem',
  'um chinelo que resolve briga de irmão',
  'a raiva de descobrir o preço do Uber surge',
  'aquele parente que só fala de política no almoço',
  'um professor particular de paquera',
  'a vergonha de mandar áudio errado pro chefe',
  'meu estômago roncando na hora do silêncio',
  'um pastor cobrando cartão de crédito no altar',
  'a saudade disfarçada de curtida no post antigo',
  'um amigo que empresta carregador e some',
  'a fila do busão lotado às 6h',
  'meu currículo com foto de 10 anos atrás',
  'um karaokê improvisado no ônibus',
  'a raiva de trocar o Wi-Fi e ninguém avisar a senha nova',
  'um sogro contando a mesma piada há 20 anos',
  'a coragem de responder o chefe em maiúsculas',
  'meu abraço apertado demais no primeiro encontro',
  'um pastor prometendo milagre parcelado',
  'a fé de quem acredita em previsão do tempo',
  'aquele silêncio na chamada de vídeo travada',
  'um tio contando vantagem sobre os anos 90',
  'a vergonha de cochilar em reunião online',
  'meu vizinho testando o alarme às 3 da manhã',
  'um crush comentando só os stories dos outros',
  'a raiva de ficar sem sinal na hora do plot twist',
  'um padre torcendo escondido pro time rival',
  'a saudade que só some com pizza',
  'um evangélico dublando funk baixinho',
  'a coragem de terminar por mensagem de voz',
  'meu chefe chamando "só um minutinho" às 17h58',
  'um pastor com anel maior que aliança de noiva',
  'a fila do RH pra pedir aumento',
  'aquele match que só chama pra jogo',
  'um tio zap virando repórter de plantão',
  'a vergonha de escorregar de chinelo no shopping',
  'meu orgulho travando o pedido de desculpas',
  'um cunhado que só aparece na hora da churrasqueira',
  'a raiva de descobrir que o boleto já venceu',
  'um exorcista cobrando por PIX parcelado',
  'a saudade que ataca depois da terceira dose',
  'um professor comentando a vida amorosa da turma',
  'a vergonha de mandar beijo pro grupo errado',
  'meu estagiário respondendo "ok" pra tudo',
  'um pastor discursando sobre Bitcoin',
  'a fila da farmácia às 23h59',
  'aquele "visto" sem resposta há três dias',
  'um sogro perguntando quando vem neto',
  'a coragem de pedir aumento numa sexta-feira',
  'meu vizinho comprando furadeira nova todo mês',
  'um crush que só curte, nunca comenta',
  'a raiva de perder o sinal no jogo decisivo',
  'um padre comentando o preço da gasolina',
  'a vergonha de rir alto no cinema silencioso',
  'meu ex comentando indireta no status',
  'um tio contando piada que ninguém pediu',
  'a fé de quem acredita em dieta de segunda',
  'um pastor cobrando fé em espécie',
  'a saudade que vira ligação bêbada',
  'aquele grupo do trabalho que só fala besteira',
  'um professor de dança se achando',
  'a vergonha de escorregar na saída da igreja',
  'meu chefe achando que fim de semana é feriado',
  'um cunhado emprestando ferramenta e sumindo',
  'a raiva de perder o desconto por um minuto',
  'um vidente de shopping cobrando por PIX',
  'a coragem de mandar oi pra ex às 3 da manhã',
  'um padre com playlist secreta de pagode',
  'a fila da rodoviária no fim de ano',
  'aquele silêncio depois de um puxão de orelha',
  'um tio comentando sobre o time errado',
  'a vergonha de gritar gol no time perdedor',
  'meu vizinho testando bateria elétrica às 6h',
  'um pastor prometendo prosperidade em dobro',
  'a saudade que some com um café requentado',
  'um sogro comparando genro com sobrinho',
  'a raiva de descobrir que a promoção acabou ontem',
  'um crush comentando meme de outra pessoa',
  'a coragem de responder áudio com áudio maior',
  'meu chefe achando reunião de sábado normal',
  'um cunhado que só chega na hora da sobremesa',
  'a fé em resolução de ano novo que dura três dias',
  'um pastor discursando sobre criptomoeda no culto',
  'a fila do caixa que sempre trava no cartão',
];
